feat(players): Attackers
YimMenu/YimMenu pull request #1050
Opened 2023-03-06 01:46 UTC by JDMJay

2023-03-06 12:09 UTC, yasmasdas commented on src/views/players/player/player_attacker.cpp
> +			components::button("Gooch Test", [] {
"Gooch test?"
Rename to something like send gooch

2023-03-06 12:09 UTC, yasmasdas commented on src/views/players/player/player_attacker.cpp
> +			components::button("Mugger Test", [] {
"Mugger test?"
Rename to something like send Mugger

2023-03-06 12:13 UTC, yasmasdas commented on src/util/toxic.hpp
> +		PED::SET_PED_FIRING_PATTERN(ped, 0xC6EE6B4C);
rage::joaat("FIRING_PATTERN_FULL_AUTO") not 0xC6EE6B4C for readability

2023-03-06 13:56 UTC, yasmasdas commented on src/views/players/player/player_attacker.cpp
> +				*script_global(1853348).at(834).at(1).as<Player*>() = g_player_service->get_selected()->id();
outdated gpbd_fm_1 global use [the class](https://github.com/Yimura/GTAV-Classes/blob/master/script/globals/GPBD_FM.hpp) like (code is example maybe not correct)
pid = ...
scr_globals::gpbd_fm_1.as<GPBD_FM*>()->Entries[self::id].GangCallRequestedServices = 0
scr_globals::gpbd_fm_1.as<GPBD_FM*>()->Entries[self::id].GangCallTarget = pid

2023-03-06 18:15 UTC, Yimura commented on src/views/players/player/player_attacker.cpp
> +			components::button("Gooch Test", [] {
I think this is an old test option that @maybegreat48 added.

2023-03-06 18:18 UTC, JDMJay commented on src/views/players/player/player_attacker.cpp
> +			components::button("Gooch Test", [] {
yea I removed it from misc and added it into attackers

2023-03-06 22:44 UTC, binded-zz commented
could you add the greifer jeus there was a few others that another menu had i for get what they was but i think chris something some Elvis  looking dude idk what there names was but they was cool 

some was just the dudes and some was with cars one was a bike and another was the truck with a ram on it 

we can already send attacker peds and body guards  
please can we have a few ready under players  i like to send them to dicks that are in god and killing every one every where's

2023-03-07 04:12 UTC, JDMJay commented on src/views/players/player/player_attacker.cpp
> +				*script_global(1853348).at(834).at(1).as<Player*>() = g_player_service->get_selected()->id();
not sure if i have done this correctly so I'm going to leave it unresolved for now

2023-03-07 16:40 UTC, yasmasdas commented on src/views/players/player/player_attacker.cpp
> +				*script_global(1853348).at(834).at(1).as<Player*>() = g_player_service->get_selected()->id();
@JDMJay You did not do it correct. and to add to that what I gave was example code
so if my example works (untested) your code should be

```
components::button("Send Mugger", [] { 
scr_globals::gpbd_fm_1.as<GPBD_FM*>()->Entries[self::id].GangCallRequestedServices = 0;
scr_globals::gpbd_fm_1.as<GPBD_FM*>()->Entries[self::id].GangCallTarget = g_player_service->get_selected()->id();
});
```

2023-03-08 03:35 UTC, JDMJay commented
> could you add the greifer jeus there was a few others that another menu had i for get what they was but i think chris something some Elvis looking dude idk what there names was but they was cool
> 
> some was just the dudes and some was with cars one was a bike and another was the truck with a ram on it
> 
> we can already send attacker peds and body guards please can we have a few ready under players i like to send them to dicks that are in god and killing every one every where's
> 
> wow after looking at what you added you added way more then i thought

I’m pretty sure tupoyemenu has that feature if @tupoy-ya  wants to contribute it he can I’m not gonna paste his code in for that sake but for now go use tupoyemenu if you want those type of trolling features etc

2023-03-08 14:08 UTC, binded-zz commented
> > could you add the greifer jeus there was a few others that another menu had i for get what they was but i think chris something some Elvis looking dude idk what there names was but they was cool
> > some was just the dudes and some was with cars one was a bike and another was the truck with a ram on it
> > we can already send attacker peds and body guards please can we have a few ready under players i like to send them to dicks that are in god and killing every one every where's
> > wow after looking at what you added you added way more then i thought
> 
> I’m pretty sure tupoyemenu has that feature if @tupoy-ya wants to contribute it he can I’m not gonna paste his code in for that sake but for now go use tupoyemenu if you want those type of trolling features etc


i do use tupoyemenu he has the jeus one there but i think he said he broke it , i like his menu layout i can have the main menu and players menu open at the same times
-

there was a guy tyackman who had the other ones as well i want to say something like chris freeman or something like that 
his menu is now only ym base only now 

was just hoping i could see them in the main branch 
either way you added way more then i was even asking for if i read any of the stuff right  i think like send tanks, rc , lazer  
i dont remember 

but thanks for all of your hard work thank you

2023-03-09 11:16 UTC, Yimura requested changes

2023-03-09 11:16 UTC, Yimura commented on src/util/toxic.hpp
> +	inline void Spawn_Attackers(Hash vehicle, float z)
Function name doesn't follow code styling guidelines, please see CONTRIBUTING.md.

2023-03-09 11:16 UTC, Yimura commented on src/views/players/player/player_attacker.cpp
> +#include <script\globals\GPBD_FM.hpp>
Use forwards facing slashes for file paths.

2023-03-09 22:44 UTC, maybegreat48 commented on src/views/players/player/player_attacker.cpp
> +		if (ImGui::TreeNode("Attackers"))
You should probably implement this in the ped spawner by adding an option to set the ped in a vehicle
The Gooch and the mugger can go in toxic

2023-03-09 22:50 UTC, maybegreat48 commented on src/util/toxic.hpp
> +		PED::ADD_RELATIONSHIP_GROUP("_HOSTILE_JESUS", &relationshipGroup);
Custom relgroups do not sync in MP
```c++
PED::SET_PED_RELATIONSHIP_GROUP_HASH(ped, RAGE_JOAAT("HATES_PLAYER"));
```
can be used instead

2023-03-09 23:13 UTC, JDMJay commented on src/views/players/player/player_attacker.cpp
> +		if (ImGui::TreeNode("Attackers"))
This is just for presets I will do this is a different pr

2023-03-10 00:25 UTC, JDMJay commented on src/util/toxic.hpp
> +		PED::ADD_RELATIONSHIP_GROUP("_HOSTILE_JESUS", &relationshipGroup);
Kinda confused how to use this

2023-03-10 10:04 UTC, maybegreat48 commented on src/util/toxic.hpp
> +		PED::ADD_RELATIONSHIP_GROUP("_HOSTILE_JESUS", &relationshipGroup);
Replace
```c++
PED::SET_PED_RELATIONSHIP_GROUP_HASH(ped, relationshipGroup);
```
With
```c++
PED::SET_PED_RELATIONSHIP_GROUP_HASH(ped, RAGE_JOAAT("HATES_PLAYER"));
```
And remove
```c++
static const Hash playerGroup = rage::joaat("PLAYER");
static const Hash civGroup    = rage::joaat("CIVMALE");
static const Hash femCivGroup = rage::joaat("CIVFEMALE");

Hash relationshipGroup;
PED::ADD_RELATIONSHIP_GROUP("_HOSTILE_JESUS", &relationshipGroup);

PED::SET_RELATIONSHIP_BETWEEN_GROUPS(5, relationshipGroup, playerGroup);
PED::SET_RELATIONSHIP_BETWEEN_GROUPS(5, relationshipGroup, civGroup);
PED::SET_RELATIONSHIP_BETWEEN_GROUPS(5, relationshipGroup, femCivGroup);
```

2023-03-10 11:04 UTC, yasmasdas commented on src/views/players/player/player_attacker.cpp
> +				scr_globals::gpbd_fm_1.as<GPBD_FM*>()->Entries[self::id].GangCallRequestedServices;
my bad for giving bad example that had a error last time but i did say it was untested.
But now what you did you just put the line and are accessing it but not doing anything with it.

you should use [Set(0) to set bit to 0](https://github.com/Yimura/GTAV-Classes/blob/master/script/types.hpp#L76) on GangCallRequestedServices as its type is a SCR_BITSET

2023-03-23 13:39 UTC, BeztNA commented
anything new?

2023-04-03 23:17 UTC, DayibBaba commented
How we spawn attackers feels quite limited to me. Id be up for a lil project to make it robust and customizable. Like vehicle choice, spawn manner, group size and maybe even track spawned attackers for extended features. A networked environment makes this quite a challenge, but I think I could manage something rather close to the scrips such as am_gang_call.

2023-04-06 18:58 UTC, yasmasdas commented
> How we spawn attackers feels quite limited to me. Id be up for a lil project to make it robust and customizable. Like vehicle choice, spawn manner, group size and maybe even track spawned attackers for extended features. A networked environment makes this quite a challenge, but I think I could manage something rather close to the scrips such as am_gang_call.

I'm not a particular fan of this system either other then for the Send Mugger feature which still hasn't been correctly implemented.

2023-05-02 01:44 UTC, Rxann commented
I do believe as though another attacker system(squad spawner) has been implemented, this can be closed.

2023-07-17 14:23 UTC, Yimura commented
Stale PR

2023-07-17 14:23 UTC, closed without merging