feat(cache): expand ped
YimMenu/YimMenu pull request #1156
Opened 2023-03-29 12:41 UTC by Aure7138

The current two caching methods cannot read componentpeds_a_c.rpf, this pr adds a third caching method - cache on init and expand the number of peds on this basis

2023-03-29 12:43 UTC, Aure7138 commented
Currently finished adding a third caching method, everything is fine, the next step is to expand ped

![image](https://i.imgur.com/pm4xB13.png)
![image](https://i.imgur.com/L4MsmjE.png)

If anyone has any suggestions please let me know

2023-03-29 12:49 UTC, xiaoxiao921 commented
long time since I wrote this but isnt hooking GetDevice better when injecting before game load?

2023-03-29 12:51 UTC, xiaoxiao921 commented
The whole point is that you don't have to use any yim packfile related functions and just utilize the fact that game is already reading all the files from the rpf as the game load, then you just profit off that

oh yeah another issue: the game doesnt load all dlc rpfs when loading in SP, meaning that they have to go to MP directly

2023-03-29 19:21 UTC, Aure7138 commented
> long time since I wrote this but isnt hooking GetDevice better when injecting before game load?

will try that one later

> The whole point is that you don't have to use any yim packfile related functions and just utilize the fact that game is already reading all the files from the rpf as the game load, then you just profit off that
> 
> oh yeah another issue: the game doesnt load all dlc rpfs when loading in SP, meaning that they have to go to MP directly

Ah, I see, the hook currently still need yim packfile, to do this probably need hook other functions, I'll try
By the way, I tried SP and MP, the amount seems to be the same, because the hook is special?

![image](https://i.imgur.com/jLPllHz.png)
Get 1019 peds, need a method to get ped type from CPedModelInfo

2023-03-31 14:31 UTC, Yimura requested changes

2023-03-31 14:31 UTC, Yimura commented on src/services/gta_data/gta_data_service.cpp
> +					std::strncpy(it->m_ped_type, ped_types[*(uint32_t*)((uintptr_t)info + 0x138)].c_str(), sizeof(it->m_ped_type));
Please don't use a static offset, modify the class on GTAV-Classes repo.

2023-04-01 16:37 UTC, Yimura approved these changes

2023-04-01 16:37 UTC, merged