Vehicle control & Summon
YimMenu/YimMenu pull request #1175
Opened 2023-04-02 14:14 UTC by DayibBaba

I made this feature at the request of the following issues; #1114 and #1168. The feature is simple and basic as of now. The main premise is to imitate Rockstars remote vehicle control menu for all cars (Not only personal vehicles). Vehicle related operations can be executed both within and outside the car. Such operations consists of but are not limited to; locking doors, opening/closing doors, activating/deactivating lights, operating convertible roofs and several more. Per request the window is standalone and not part of the main UI. It can be activated by a hotkey set in the Hotkeys settings or just in the Vehicle UI. I have imitated the scripts as much as I could with features such as the animations and sounds that play.

Some pictures:
![image](https://user-images.githubusercontent.com/79384354/229358229-562b3f19-a749-42fd-83a1-6d43745467d0.png)
![image](https://user-images.githubusercontent.com/79384354/229358234-c0d61b2e-d21f-4525-9d80-ea3c89724aa2.png)

Current problems:
-Since the menu is made with ImGui, the cursor is required to make us of it. However, the cursor is only activated when the main UI is on limiting the users screen when using the feature. 
-For some reason the summon feature won't work on Personal Vehicles. The Invisible driver just wont execute its task. Any help on this one is appreciated.

2023-04-04 17:04 UTC, DayibBaba commented
After some troubleshooting I have discovered that either the scripts or some other loop is making the invisible driver exit the vehicle on the summon feature if vehicle access is set to 'Passengers' in the interaction menu. I have looked through the scripts to find if the access is synced with a global to make a little work-around but was unsuccessful.

2023-04-05 11:41 UTC, maybegreat48 commented on src/gta/enums.hpp
> +
Adding leaked source code to YimMenu is not a good idea. The menu is under constant observation by Rockstar and P2Cs that may want to be rid of us

You can obviously use the leaks to develop stuff, but try not to make it obvious

2023-04-05 11:41 UTC, maybegreat48 commented on src/views/view_vehicle_control.cpp
> +				    g_vehicle_control_service.m_controlled_vehicle.engine ? false : true,
`!g_vehicle_control_service.m_controlled_vehicle.engine`

2023-04-05 11:41 UTC, maybegreat48 commented on src/views/debug/view_debug_misc.cpp
> +			components::button("Tp to safe pos", [] {
All interactive UI elements should use Title Case for consistency. So it should be `TP To Safe Pos`

2023-04-05 11:41 UTC, maybegreat48 commented on src/services/vehicle/vehicle_control_service.hpp
> +		std::map<int, std::string_view> radiostations;
This isn't used anywhere

2023-04-05 12:16 UTC, DayibBaba commented on src/services/vehicle/vehicle_control_service.hpp
> +		std::map<int, std::string_view> radiostations;
It was meant for a future feature which I laughably failed to implement

2023-04-05 12:19 UTC, DayibBaba commented on src/views/view_vehicle_control.cpp
> +				    g_vehicle_control_service.m_controlled_vehicle.engine ? false : true,
I have had minor issues regarding similar code. Common sense would dictate that; 
If (action) neon_lights( !vehicle.neonlights).
However this seemed to fail almost always, and inserting the value without the negative operand somehow worked.

2023-04-05 12:20 UTC, DayibBaba commented on src/gta/enums.hpp
> +
Should I remove those enums or just the comments alongside them?

2023-04-05 12:22 UTC, DayibBaba commented
> After some troubleshooting I have discovered that either the scripts or some other loop is making the invisible driver exit the vehicle on the summon feature if vehicle access is set to 'Passengers' in the interaction menu. I have looked through the scripts to find if the access is synced with a global to make a little work-around but was unsuccessful.

This has been bypassed now.

2023-04-05 12:23 UTC, Yimura commented on src/gta/enums.hpp
> +
We can recreate the enums from reverse engineering but we can't use leaks directly.

It's best you remove the whole enum.

2023-04-05 12:38 UTC, Yimura requested changes

2023-04-05 12:38 UTC, Yimura commented on src/services/vehicle/vehicle_control_service.hpp
> +#define VEH_OP_ANIM "FOB_CLICK"
Prefer `constexpr auto` over macro's.

2023-04-05 15:10 UTC, xiaoxiao921 commented on src/views/view_vehicle_control.cpp
> +				    g_vehicle_control_service.m_controlled_vehicle.engine ? false : true,
`g_vehicle_control_service.m_controlled_vehicle.engine ? false : true`

is identical to `!g_vehicle_control_service.m_controlled_vehicle.engine` though

2023-04-05 17:54 UTC, merged