Admin checking protection
YimMenu/YimMenu pull request #1187
Opened 2023-04-04 15:37 UTC by Rxann

This pr adds a protection for checking to see if there is a player in your lobby with the same ID as a rockstar employee. I am an intermediate coder at C++. This is my best attempt.

Current Issues:
1: Seems to be resource intensive. maybe caching could be used?

Source for the IDs:
https://github.com/RockstarGamesAdminsStaffGamertags/List and the repo's subsequent PR.

2023-04-04 15:39 UTC, Rxann commented
should I merge the changes from master in this branch?

2023-04-04 15:40 UTC, xiaoxiao921 requested changes

2023-04-04 15:40 UTC, xiaoxiao921 commented on src/backend/looped/system/admin_check.cpp
> +			std::vector<std::string> admin_names = {"67241866", "89288299", "88439202", "179848415", "184360405", "184359255", "182860908", "117639172", "142582982", "115642993", "100641297", "116815567", "88
move the std::vector outside of the on_tick function (put it just above) and turn it into a constexpr std::array

2023-04-04 15:40 UTC, xiaoxiao921 commented on src/backend/looped/system/admin_check.cpp
> +			std::vector<std::string> admin_names = {"67241866", "89288299", "88439202", "179848415", "184360405", "184359255", "182860908", "117639172", "142582982", "115642993", "100641297", "116815567", "88
Why are you using strings there in the first place? use the `id` type

2023-04-04 15:40 UTC, xiaoxiao921 commented on src/backend/looped/system/admin_check.cpp
> +				auto found = std::find(admin_names.begin(), admin_names.end(), std::to_string(plyr.second->id()));
Why are you using strings there in the first place? use the same type as the `id` field

2023-04-04 15:42 UTC, Yimura reviewed
I would put this check in the on player join hook, for the RockstarId’s don’t use strings but instead use a better suited type like uint64_t.

2023-04-04 15:44 UTC, Rxann commented
> I would put this check in the on player join hook, for the RockstarId’s don’t use strings but instead use a better suited type like uint64_t.

So, what would I need to change to move it to the on player hook?

2023-04-04 15:47 UTC, tupoy-ya requested changes

2023-04-04 15:47 UTC, tupoy-ya commented on src/backend/looped/system/admin_check.cpp
You should do this check in `assign_physical_index.cpp`.
Also you should put this file into `backend/commands/` instead of `backend/looped/`.

2023-04-04 15:47 UTC, tupoy-ya commented on src/backend/looped/system/admin_check.cpp
> +			// taken from https://github.com/RockstarGamesAdminsStaffGamertags/List and prs
Why not link the fork directly?

2023-04-04 15:47 UTC, tupoy-ya commented on src/views/settings/view_protection_settings.cpp
> +		ImGui::Checkbox("Admin Check", &g.protections.admin_check);
You should use `components::command_checkbox` here.

2023-04-04 16:02 UTC, Rxann commented on src/backend/looped/system/admin_check.cpp
> +				auto found = std::find(admin_names.begin(), admin_names.end(), std::to_string(plyr.second->id()));
I am using uint64_t now

2023-04-04 16:03 UTC, Rxann commented on src/backend/looped/system/admin_check.cpp
> +			// taken from https://github.com/RockstarGamesAdminsStaffGamertags/List and prs
I copied the data from the repo myself

2023-04-04 16:05 UTC, tupoy-ya commented on src/backend/commands/self/admin_check.cpp
> +				auto found = std::find(admin_names.begin(), admin_names.end(), std::to_string(plyr.second->id()));
Also just noticed that you are checking `plyr.second->id()` this is NOT RID if you want to get RID use `plyr.second->get_net_data()->m_gamer_handle.m_rockstar_id`

2023-04-04 16:10 UTC, Rxann commented on src/backend/looped/system/admin_check.cpp
How can I implement this check in the file?

2023-04-04 16:24 UTC, Rxann commented
How can I execute the command in the assign_physical_index?

2023-04-04 16:25 UTC, Yimura commented
> How can I execute the command in the assign_physical_index?

Which command are you planning to execute?
Also I would highly recommend you to code locally on your computer instead of using Github browser to edit code.

2023-04-04 16:26 UTC, Rxann commented
> > How can I execute the command in the assign_physical_index?
> 
> Which command are you planning to execute? Also I would highly recommend you to code locally on your computer instead of using Github browser to edit code.

I use visual studio code on my local machine. But, I want to execute the admin_check because that's what was suggested to me on how to implement this feature.

2023-04-04 16:38 UTC, Yimura commented
> I use visual studio code on my local machine. But, I want to execute the admin_check because that's what was suggested to me on how to implement this feature.

For this you'd make a function which you would then call, no need to execute a command to offer that functionality.

2023-04-04 16:43 UTC, Rxann commented
Alright, I will do this in the assign_physical_index.cpp file correct?

2023-04-04 21:21 UTC, Rxann commented
should I just close this pr until I figure out what file I need to implement this feature in?

2023-04-04 21:30 UTC, xiaoxiao921 commented
You just move the rockstar id check inside the `hooks::assign_physical_index` function, this function is called when a player join, aka when a potential admin could be joining your session

2023-04-04 21:41 UTC, Rxann commented
Alright, I will work on this

2023-04-04 21:58 UTC, Rxann commented
I have moved the code successfully, plus I tested it in a public lobby and it works.

2023-04-04 22:16 UTC, Yimura requested changes

2023-04-04 22:16 UTC, Yimura commented on src/hooks/player_management/assign_physical_index.cpp
> +		std::vector<std::uint64_t> admin_names = {67241866, 89288299, 88439202, 179848415, 184360405, 184359255, 182860908, 117639172, 142582982, 115642993, 100641297, 116815567, 88435319, 64499496, 174623
Make this `std::vector<uint64_t>` static or move it outside the function.

And rename the variable from `admin_names` to `admin_rids`.

2023-04-04 22:16 UTC, Yimura commented on src/hooks/player_management/assign_physical_index.cpp
> +		});
Don't iterate all players, only the one that joined. This function triggers on player join and on leave so make sure you add the functionality inside the correct if statement.

This function triggers for only one person at the time.

2023-04-05 15:06 UTC, Yimura approved these changes
Looks good to me, waiting for the other guy's opinions.

2023-04-05 15:08 UTC, xiaoxiao921 approved these changes

2023-04-05 15:10 UTC, tupoy-ya approved these changes
Didn't test.
No toggles, but not needed.

2023-04-05 15:12 UTC, Rxann commented
Thank you guys for helping me with the code btw

2023-04-05 16:57 UTC, merged