Ipl
YimMenu/YimMenu pull request #1283
Opened 2023-04-23 21:16 UTC by Primexz

fixes #1271
refs https://github.com/YimMenu/Translations/pull/32

2023-04-23 22:06 UTC, maybegreat48 commented
1. Active IPLs should be removed when a new one is loaded
2. This does not need a new tab (teleport should work)

2023-04-27 12:13 UTC, Yimura requested changes
Is the comment from @maybegreat48 implemented? I've merged the translations on the Translation repo.

2023-04-27 12:18 UTC, Primexz commented
> Is the comment from @maybegreat48 implemented? I've merged the translations on the Translation repo.

Not yet. will do that today

2023-04-29 11:15 UTC, Yimura approved these changes

2023-04-29 11:29 UTC, merged