Refactor commands so that hard reference to variable are used instead of hardcoded strings
YimMenu/YimMenu pull request #1325
Opened 2023-05-03 02:40 UTC by xiaoxiao921

string control flow is evil:

- code can break while still compiling just fine
- it's difficult to read and understand
- it can lead to runtime errors that are hard to trace

By using hard references to variables instead of hardcoded strings, we can improve the reliability and readability of the codebase. This pull request refactors the commands to use hard references to variables wherever possible. This change will make the code more robust and easier to maintain in the long run.

For example, several buttons did absolutely nothing because the strings used in the `view_session.cpp` for the "all" variants of some of these commands were never implemented. I have removed them for the time being, but of course they can be reinstated when someone wants to implement them.

Note: The hotkey system and the command executor system still use string control flow.

With the way the hotkeys are currently written, we could move them to variable references, but I don't think we really want that because of the current system which is a kind of crappy hard-coded system: we could have a gui or even a command executor `bind` system where we could have any command to shortcut instead of a hard-coded list in the code as we currently have.

2023-05-03 04:04 UTC, FireFox101889 commented
Agree! Obviously not a code reviewer but looks great

2023-05-04 20:17 UTC, Yimura requested changes

2023-05-04 20:17 UTC, Yimura commented on src/backend/commands/player/kick/null_function_kick.hpp
> +#include "pointers.hpp"
These includes can be moved to the CPP file.

2023-05-04 20:17 UTC, Yimura commented on src/backend/commands/player/kick/script_host_kick.hpp
> +#include "util/scripts.hpp"
These includes can be moved to the CPP file.

2023-05-04 20:17 UTC, Yimura commented on src/backend/commands/player/misc/clear_wanted_level.hpp
> +#include "util/globals.hpp"
These includes can be moved to the CPP file.

2023-05-04 20:17 UTC, Yimura commented on src/backend/looped/self/no_water_collision.hpp
> +#include "backend/looped/looped.hpp"
looped.hpp?

2023-05-04 20:17 UTC, Yimura commented on src/backend/looped/self/part_water.hpp
> +#include "backend/looped/looped.hpp"
looped.hpp?

2023-05-04 20:17 UTC, Yimura commented on src/backend/looped/vehicle/speedo_meter.hpp
> +#include "backend/looped/looped.hpp"
looped.hpp?

2023-05-05 11:27 UTC, Yimura approved these changes
@maybegreat48, any insights on the change?

2023-05-15 15:24 UTC, xiaoxiao921 commented
Will be merged after most PRs so that its not a burden to others

2023-08-23 11:23 UTC, Yimura commented
Stale PR

2023-08-23 11:23 UTC, closed without merging