debug misc translations
YimMenu/YimMenu pull request #1331
Opened 2023-05-05 01:46 UTC by Rxann

translates the misc debug UI

depends on [#34](https://github.com/YimMenu/Translations/pull/34)

2023-05-12 15:58 UTC, Rxann commented
any insight on this?

2023-06-05 19:47 UTC, Yimura requested changes

2023-06-05 19:47 UTC, Yimura commented on src/views/settings/view_protection_settings.cpp
> +		ImGui::Checkbox("RECIEVE_PICKUP"_T.data(), &g.protections.receive_pickup);
Typo "RECIEVE" => "RECEIVE"

2023-06-10 13:15 UTC, Yimura approved these changes

2023-06-10 13:21 UTC, merged