Context menu: Fixed janky entity detection
YimMenu/YimMenu pull request #1366
Opened 2023-05-21 13:45 UTC by DayibBaba

The feature was prioritizing entity types due to the nature of its iteration. It stuck to certain entities while others were closer to the center of the screen. I have decided to stick with its way of scanning the pools, but added a different (small) algorithm to fix the said issue.

2023-05-21 15:48 UTC, DayibBaba commented
It appears this addition still remains unreliable. I might just try and rewrite some of the code.

2023-06-05 19:25 UTC, Yimura requested changes

2023-06-05 19:25 UTC, Yimura commented on src/services/context_menu/context_menu_service.cpp
> +			const auto get_closest_to_center = [this, &distance](auto entity_getter_func) -> auto {
You can modify the `get_closest_to_center` function to return an entity pointer if it finds one close to the middle of the screen.
Then simplify the code inside the `get_closest_to_center` to not assign to m_veh_pointer, m_ped_pointer, m_prop_pointer but instead do it where you return the entity.

2023-06-05 19:25 UTC, Yimura commented on src/services/context_menu/context_menu_service.cpp
>  			got_an_entity |= get_closest_to_center(pools::get_all_props);
These calls to `get_closest_to_center` can have their return values modified to m_veh_pointer, m_ped_pointer, m_prop_pointer.
You can then also move those member values to normal stack values within the function (aka not part of the class).

2023-06-05 19:25 UTC, Yimura commented on src/services/context_menu/context_menu_service.cpp
> +			}
Code duplication, can be made into a lambda like `get_closest_to_center`.

2023-06-05 19:25 UTC, Yimura commented on src/services/context_menu/context_menu_service.hpp
> +		rage::fwEntity* m_prop_pointer{};
Can be removed after the proposed changes to `get_closest_to_center` have been implemented.

2023-06-05 20:25 UTC, DayibBaba commented
This method seems unreliable. I will try and rewrite the entity scanner in a different manner.

2023-06-05 20:25 UTC, closed without merging