Tunables service fix and theme changes
YimMenu/YimMenu pull request #1507
Opened 2023-06-22 20:51 UTC by maybegreat48

* Added a script connection service (might be buggy, haven't tested it completely)
* Added an option to display the local player's position in the overlay
* Added notes to the player database
* Changed the default color palette from black to green (and added some basic theme customization)

Fixes #1504 
Fixes #1498
Fixes #1469 
Fixes #1442 
Fixes #1433 
Closes #618

2023-06-22 21:05 UTC, Yimura approved these changes, later dismissed

2023-06-22 21:16 UTC, xiaoxiao921 requested changes, later dismissed
small nitpicks here and there, good amount of work nontheless

2023-06-22 21:16 UTC, xiaoxiao921 commented on src/services/tunables/tunables_service.cpp
> +					int id = SYSTEM::START_NEW_SCRIPT_WITH_NAME_HASH_AND_ARGS(RAGE_JOAAT("tuneables_processing"), (Any*)args, sizeof(args) / 8, 1424);
you defined a constexpr for this, may aswell use it

2023-06-22 21:16 UTC, xiaoxiao921 commented on src/views/core/view_overlay.cpp
> +				    g_local_player->get_position()->x,
a local variable for this would be nice

2023-06-22 21:16 UTC, xiaoxiao921 commented on src/services/script_connection/script_connection.cpp
> +#if 0
why is this here

2023-06-22 21:16 UTC, xiaoxiao921 commented on src/gui.cpp
> +		ImGui::PopStyleColor();
this whole part scream for a wrapper function that also increment a variable which is then used for forloop

2023-06-22 21:16 UTC, xiaoxiao921 commented on src/invoker.cpp
> +					//_call_asm(&m_call_context, handler, g_pointers->m_gta.m_native_return);
remove commented code completly
could also remove the .asm file I guess?

2023-06-22 21:18 UTC, SkiddyToast commented on src/hooks/script/script_vm.cpp
> +		if (program->m_name_hash == RAGE_JOAAT("net_tunable_check")) // not sure what starts this, but it tries to crash the game and must be blocked
This script has never been used/started, there's no point in adding this.

2023-06-23 00:33 UTC, maybegreat48 commented on src/services/script_connection/script_connection.cpp
> +#if 0
It is currently broken and causes the script to unload early. Keeping the code as it wouldn't be stored in the history when the PR gets squashed and merged as a single commit

2023-06-23 01:12 UTC, frostyperflix commented on src/backend/commands/player/toxic/kick_from_interior.cpp
> +				});
This looks really clean. 😄
Very nice addition!

2023-06-23 01:16 UTC, frostyperflix reviewed
Looks pretty good to me (apart from what people have already commented about). I am not a code-reviewer and I just quickly looked through so my review is just a comment as it provides no significance. I am curiously waiting for this to be merged as I sense it might fix a couple issues that aren't related.

2023-06-23 06:43 UTC, Yimura approved these changes

2023-06-23 06:43 UTC, merged