Mission fixes and modder detection improvements
YimMenu/YimMenu pull request #1598
Opened 2023-07-04 22:13 UTC by maybegreat48

Fixes #1569 
Fixes #1559 
Fixes #1556 
Added new modder detections
Transition state UI now shows host broadcast received percent
Improved crash protections

2023-07-04 22:28 UTC, Yimura requested changes

2023-07-04 22:28 UTC, Yimura commented on src/backend/context/chat_command_context.cpp
> +#include "fiber_pool.hpp"
Random include added

2023-07-04 22:28 UTC, Yimura commented on src/hooks/protections/received_array_update.cpp
> +#include "util/misc.hpp"
Unused includes?

2023-07-04 22:36 UTC, maybegreat48 commented on src/backend/context/chat_command_context.cpp
> +#include "fiber_pool.hpp"
I've removed an include from a header file and stuff that implicitly relied on it being included broke

2023-07-04 22:36 UTC, maybegreat48 commented on src/hooks/protections/received_array_update.cpp
> +#include "util/misc.hpp"
I've removed an include from a header file and stuff that implicitly relied on it being included broke

2023-07-05 07:29 UTC, Yimura commented on src/hooks/protections/received_array_update.cpp
> +#include "util/misc.hpp"
Alright.

2023-07-05 07:29 UTC, Yimura commented on src/backend/context/chat_command_context.cpp
> +#include "fiber_pool.hpp"
Alright.

2023-07-05 07:29 UTC, Yimura approved these changes

2023-07-05 07:30 UTC, merged