Persist Weapons
YimMenu/YimMenu pull request #1647
Opened 2023-07-08 16:31 UTC by gir489returns

Updated GetVehicleInfoForClanLogo.
Made Ammunation into a CollapsingHeader.

2023-07-08 22:18 UTC, Yimura requested changes

2023-07-08 22:18 UTC, Yimura commented on src/services/persist_weapons/persist_weapons.h
Use explicit CPP header `.hpp`.

2023-07-08 22:18 UTC, Yimura commented on src/services/persist_weapons/weaponloadout_json.h
Use explicit CPP header `.hpp`.

2023-07-09 11:07 UTC, DayibBaba commented
I wonder if this could be done with other players. Idk whether we can gather data on the weapons of other players, but im certain we can give them with a network event.

2023-07-09 14:25 UTC, gir489returns commented
> I wonder if this could be done with other players. Idk whether we can gather data on the weapons of other players, but im certain we can give them with a network event.

You cannot give them components or set the tint. You can only give them weapons and the ammo for it. I tried that before when developing BBv2.

2023-07-09 15:26 UTC, Yimura submitted a review, later dismissed

2023-07-09 16:14 UTC, Yimura approved these changes

2023-07-09 21:01 UTC, merged