Empty lobby
YimMenu/YimMenu pull request #1812
Opened 2023-07-23 12:36 UTC by Rxann

Allows the ability to kick everyone from the lobby with one click. Also swaps the bail kick for end kick when kicking chat spammers.

2023-07-23 12:37 UTC, Yimura requested changes
Sounds pretty useless to me, I'd just send a desync to the host and that would empty the lobby as well without interrupting everyone in the lobby and breaking them apart.

2023-07-23 12:46 UTC, Rxann commented
> This implementation is pretty stupid, I'd just send a desync to the host and that would empty the lobby as well without interrupting everyone in the lobby and breaking them apart.
> 
> Not sure if desync still works like that though.

Are you sure you can desync the host? I thought in the tooltip it said "does not work on host".

2023-07-23 12:48 UTC, Yimura commented
> Are you sure you can desync the host? I thought in the tooltip it said "does not work on host".

Yes, exactly because it will backfire when used on the host.
This feature is asking for an empty session, by sending a desync to the host you will be dropped out of the lobby with everyone gone. In the end the same will be achieved without having to kick everyone from the lobby and disturbing their gameplay.

2023-07-23 12:52 UTC, Rxann commented
> > Are you sure you can desync the host? I thought in the tooltip it said "does not work on host".
> 
> Yes, exactly because it will backfire when used on the host. This feature is asking for an empty session, by sending a desync to the host you will be dropped out of the lobby with everyone gone. In the end the same will be achieved without having to kick everyone from the lobby and disturbing their gameplay.

Okay, I will reimplement. Should I continue to iterate the g_player_service and check if they are the host, or should I use another way?

2023-07-23 12:57 UTC, maybegreat48 commented
You can just use the connection manager to close all connections, or the player manager to remove all players from the session

2023-07-23 12:57 UTC, Yimura commented
> Okay, I will reimplement. Should I continue to iterate the g_player_service and check if they are the host, or should I use another way?

Check YimMenu what methods there are on if there's a better way to do it.
Being aware of what you can use in the code base is also part of being a competent coder.

2023-07-23 12:57 UTC, Yimura commented
> You can use use the connection manager to close all connections, or the player manager to remove all players from the session

That would be even better most likely.

2023-07-23 13:31 UTC, gir489returns commented
> This implementation is pretty stupid.

Another LitteTimmy™ stupid shit productions attempt to fit in. It's like he just makes random shit with whatever's exposed in the base to just make PRs. It's fucking annoying. Go back to the sandbox, Timmy.

2023-07-23 15:39 UTC, NtQueryInformationProcess commented
> > This implementation is pretty stupid.
> 
> Another LitteTimmy™ stupid shit productions attempt to fit in. It's like he just makes random shit with whatever's exposed in the base to just make PRs. It's fucking annoying. Go back to the sandbox, Timmy.

im gonna say it to you 🗣️ 🔥

2023-07-23 20:41 UTC, maybegreat48 commented on src/backend/commands/session/wipe_session.cpp
> +				g_notification_service->push_success("Empty Session", "Completed");
This should be outside the iterator callback

2023-07-23 23:42 UTC, Rxann commented
the notification has been moved outside the iterator callback

2023-07-24 19:53 UTC, Yimura approved these changes

2023-07-24 20:10 UTC, merged