Improved reaction.cpp code C++ 23
YimMenu/YimMenu pull request #1897
Opened 2023-07-31 16:21 UTC by MoneyDropLobby

Improved to C++ 23

2023-07-31 16:32 UTC, Yimura requested changes
Don't forget we have a .clang-format file, you can use it to help you format files.

Also small nitpick, why exactly is this C++23 related? At most this would just be a general code cleanup.

2023-07-31 16:32 UTC, Yimura commented on src/backend/reactions/reaction.cpp
> +    	}
Indentation is off.

2023-07-31 16:32 UTC, Yimura commented on src/backend/reactions/interloper_reaction.cpp
> +    	process_common(attacker);
Indentation is off

2023-07-31 16:56 UTC, MoneyDropLobby commented
should be fixed now

2023-07-31 17:00 UTC, Yimura requested changes
As I said before there's a formatter file in the repo, check out the repository locally and fix the indents.

Using Github's code editor fucks with indents.

2023-07-31 17:00 UTC, Yimura commented on src/backend/reactions/reaction.cpp
> +        });
Indentation is still off.

2023-07-31 17:00 UTC, Yimura commented on src/backend/reactions/interloper_reaction.cpp
> +    	process_common(attacker);
Indentation is still off.

2023-07-31 20:32 UTC, MoneyDropLobby commented
I am done.

2023-08-01 09:07 UTC, Yimura approved these changes
No further complaints.

2023-08-01 09:10 UTC, merged