Vehicle control additions & fixes
YimMenu/YimMenu pull request #1926
Opened 2023-08-05 17:03 UTC by DayibBaba

Ill draft my current changes and take any suggestion into consideration.

Changes:
- [X] Improve the method of playing animations
- [X] Convert UI elements to components to make use of in-built fiber pool usage.
- [X] Remove summon distance (Nobody seemed to need it lol).
- [X] Allow vehicles other than cars.
- [] Introduce a method of manual controlled vehicle selection.
- [] Other suggestions...

2023-08-06 19:26 UTC, GTMoraes commented
I'm using the changes on my own fork.

Few bugs I noticed so far:
- Selecting to control the Closest Vehicle and then choosing to control the Personal Vehicle, without a spawned personal vehicle, crashes the game.
- The checkmark to turn engine on/off is bugged. It's always unchecked and doesn't change according to status. Also, it only turns the engine on, when the "Use Animation" checkbox is marked, and only turns the engine off when the same checkbox is unmarked.

I'm still trying it out so far, but looks promising! Thanks for considering my suggestion to control other vehicles than the previous one.

2023-08-06 21:02 UTC, DayibBaba commented
> I'm using the changes on my own fork.
> 
> Few bugs I noticed so far:
> 
> * Selecting to control the Closest Vehicle and then choosing to control the Personal Vehicle, without a spawned personal vehicle, crashes the game.
> * When selected to control the Personal Vehicle, the checkmark to turn engine on/off is bugged. It's always unchecked and doesn't change according to status. Also, it only turns the engine on, when the "Use Animation" checkbox is marked, and only turns the engine off when the same checkbox is unmarked.
>   Using the "Last Driven", it behaves correctly, although it doesn't turn the engine on or off, when the Use Animations is checked off (which was the behavior from before this update)
> 
> I'm still trying it out so far, but looks promising! Thanks for considering my suggestion to control other vehicles than the previous one.

Thanks for the heads up. This definitely needs more before it can be considered remotely done.

2023-08-29 18:24 UTC, Yimura commented
@DayibBaba stale PR

2023-08-29 18:57 UTC, DayibBaba commented
> @DayibBaba stale PR

Not planning on working on this for the foreseeable future.

2023-09-01 03:32 UTC, GTMoraes commented
This PR as is, works reasonably OK.

The bugs I mentioned before are still present, and sometimes, switching from "Personal" to "Last driven" crashes the game when something that I can't really put my finger at, happens with the last driven vehicle. 
It's a rare event, but when it happens, it's after a mission and the vehicle despawns/disappears. I can read that the last vehicle model is a NULL and the game immediately crashes. Most of the time, though, even though the mission vehicle disappeared or whatever, it just displays the "last vehicle" as if it still existed, but does nothing. Next vehicle you enter, it works fine.

Last time I recall that it happened, was when I had to fly a police helicopter to take pictures of someone in a balcony. After the mission ended, I landed the chopper somewhere and when I opened the vehicle menu, it listed the last vehicle as NULL, then the game froze and crashed.   
But it also happened with normal vehicles.

Probably not ready for prime time, but looks close.

2023-09-04 07:44 UTC, DayibBaba commented
> This PR as is, works reasonably OK.
> 
> The bugs I mentioned before are still present, and sometimes, switching from "Personal" to "Last driven" crashes the game when something that I can't really put my finger at, happens with the last driven vehicle. 


Happens due to the personal vehicle not existing in the script. There is no check whether one exists before switching to it. The handle is fetched from a global and casted into a Vehicle. I have this fixed on my local but have recently deleted gta to reserve space for Starfield.

2023-09-30 20:47 UTC, Yimura requested changes
Waiting for PR on translation repo.

2023-09-30 20:47 UTC, Yimura commented on src/services/vehicle/vehicle_control_service.cpp
> +		case eControlledVehSelectionMode::CLOSEST: get_closest_vehicle(); break;
case, function and break on one line?

2023-10-01 09:54 UTC, DayibBaba commented on src/services/vehicle/vehicle_control_service.cpp
> +		case eControlledVehSelectionMode::CLOSEST: get_closest_vehicle(); break;
The format shortcut did this, not me.

2023-11-03 21:30 UTC, Yimura approved these changes
Should be ready to merge now, will handle the other PR's that still need their translations done.
Then after merging the translations this will go into master.

2023-11-03 23:22 UTC, merged