refactor: Modernized/optimized general code, bug fixing and more
YimMenu/YimMenu pull request #226
Opened 2022-05-21 08:29 UTC by karifeld

refactor: Utilize self globals and gui::components on most code
fix(Vehicle Preview): addresses the issues mentioned in #119

2022-05-21 10:38 UTC, xM4ddy commented
Hey looking through the changes and wondering about your decision to do something like `Vehicle vehicle = self::veh;` rather than using `self::veh`. (Not saying it's an issue just looking to clarify something.

2022-05-21 12:21 UTC, karifeld commented
well, its an optimization habit that ive carried over outside of Lua.

in Lua, if you were to run the following:
`for i = 1, 1000000 do 
   local x = math.sin(i) 
end`

`local sin = math.sin 
for i = 1, 1000000 do
    local x = sin(i) 
end`

The latter would run faster than the former. because Lua's main data structure is a table. if you were to a global function instead of a local, it will be slower because globals are stored in a table and are accessed via hash lookup. On the other hand, If you store a local variable outside a loop, the resulting code would be faster as they are accessed by index.

Now, im not expert but i dont think declaring a local variable really makes a difference in CPP.
which is why theres another reason, Readability and tidiness.

Compare both codes. one has a location variable declared and one does not.
	
	Vector3 vector;
	vector.x = self::pos.x * 2;
	vector.y = self::pos.y * 2;
	vector.z = self::pos.z * 2;
	
.

	Vector3 location = self::pos;
	
	Vector3 vector;
	vector.x = location.x * 2;
	vector.y = location.y * 2;
	vector.z = location.z * 2;
	
The latter looks neater and much more comprehensive than the former, Consistency is the most important aspect of a coding style. I think it should be the norm of best practices

2022-05-21 23:32 UTC, Yimura requested changes
In general all looks good, if you resolve the few comments I have here and there then we can merge it into master.

2022-05-21 23:32 UTC, Yimura commented on BigBaseV2/src/backend/looped/self/no_ragdoll.cpp
> -
You sure you want to always run this native, you're even executing the native when the feature is disabled, possibly causing side effects in missions. Have you properly tested this?

2022-05-21 23:32 UTC, Yimura commented on BigBaseV2/src/backend/looped/weapons/infinite_mag.cpp
> -		}
Forcefully running this native each tick even when disabled might cause side effects.

2022-05-21 23:32 UTC, Yimura commented on BigBaseV2/src/backend/looped/vehicle/fly.cpp
> +#include "gta/enums.hpp"
Sort includes alphabetically

2022-05-22 06:43 UTC, maybegreat48 commented
Infinite ammo (not infinite clip) can be simplified to ```WEAPON::SET_PED_INFINITE_AMMO(self::ped, g.weapons.infinite_ammo, NULL);```

2022-05-22 11:15 UTC, karifeld commented
@Yimura Changes have been made, let me know what you think.

@maybegreat48  Thanks for the contribution.

2022-05-22 12:06 UTC, Yimura approved these changes

2022-05-22 12:07 UTC, Yimura commented
If there are no more changes to be added then it's ready to be merged into master.

2022-05-22 12:44 UTC, karifeld commented
That should be it, you may merge at anytime

2022-05-22 13:18 UTC, Yimura commented
Alright @xM4ddy will take one final look at it and then it'll be merged.

2022-05-22 22:10 UTC, xM4ddy commented
> Infinite ammo (not infinite clip) can be simplified to `WEAPON::SET_PED_INFINITE_AMMO(self::ped, g.weapons.infinite_ammo, NULL);`

I'm trying to remember why I did that. It was actually a conscious choice actually. I may have just been some weird preference for the behavior of doing it the way I did.

2022-05-22 22:20 UTC, Yimura commented
There might be some odd scenario where the game resets the toggle.

2022-05-22 22:38 UTC, xM4ddy commented
Both seem to work so if I remember what it was and its important I'll just make another commit.

2022-05-22 22:38 UTC, merged