Optimizations
YimMenu/YimMenu pull request #2649
Opened 2023-12-27 00:23 UTC by maybegreat48

* The invoker has been rewritten to be more efficient and thread-safe
* Zydis has been replaced by the Hacker Disassembler Engine found in MinHook
* Compiler optimizations have been enabled, halving DLL size
* Refactored hooking code into a new directory
* Bug fixes

2023-12-27 11:25 UTC, Yimura requested changes

2023-12-27 11:25 UTC, Yimura commented on src/lua/natives/__pycache__/natives_gen.cpython-311.pyc
Please remove `__pycache__` folder and add it to `.gitignore`.

2023-12-27 11:25 UTC, Yimura commented on src/native_hooks/tunables.hpp
> +			g_tunables_service->register_tunable(src->get_arg<Hash>(1), src->get_arg<bool*>(2));
Intentional change from `BOOL` to `bool`?

2023-12-27 11:26 UTC, Yimura commented
Any chance we can rename the `scripts/` folder to `cmake/` and start moving some python helper scripts into a new `scripts/` folder?

I have been planning on doing this but haven't made to time to get around to it.

2023-12-27 11:51 UTC, maybegreat48 commented on src/lua/natives/__pycache__/natives_gen.cpython-311.pyc
VS didn't show me that for some reason

2023-12-27 11:55 UTC, maybegreat48 commented on src/native_hooks/tunables.hpp
> +			g_tunables_service->register_tunable(src->get_arg<Hash>(1), src->get_arg<bool*>(2));
No, but it shouldn't matter

2023-12-27 13:11 UTC, xiaoxiao921 commented
Very confused about the release with deb info stuff, do we even want all of this? Why don't we just remove all the info and just use a good classic release mode? Also the nightly never used it also unless it I'm missing something

2023-12-28 16:56 UTC, Yimura commented
> Very confused about the release with deb info stuff, do we even want all of this? Why don't we just remove all the info and just use a good classic release mode? Also the nightly never used it also unless it I'm missing something

He probably wants users to start the incentive of users taking the pdb as well so the crash dumps are easier to decipher.

2023-12-28 17:21 UTC, xiaoxiao921 commented
https://github.com/return-of-modding/ReturnOfModding/commit/aff7004aec33aea67e00dd72bf84d6bec760bd2d

2023-12-28 23:27 UTC, Yimura approved these changes
Fine by me to merge it now, I or someone else can do the change in regards to the scripts/ directory.

2023-12-29 16:07 UTC, merged