Added x64-Release-FastCompile build.
YimMenu/YimMenu pull request #2651
Opened 2024-01-01 17:47 UTC by gir489returns

The optimizations added in #2649 cause excessive build and linkage time when development. The Debug build throws a lot of pedantic errors that the runtime swallows. Until it is fixed, I suggest we use this instead, and also remove a redundant compile flag.

2024-01-02 14:41 UTC, Yimura requested changes

2024-01-02 14:41 UTC, Yimura commented on CMakeLists.txt
> +    if(OPTOMIZE)
`OPTOMIZE` => `OPTIMIZE`

2024-01-02 14:43 UTC, xiaoxiao921 commented
How about we jst have Release, ReleaseWithDebInfo, Debug config options?

Release by default should have optimization enabled anyway, i'm not sure why all the things in the cmake file are needed

2024-01-02 14:52 UTC, xiaoxiao921 commented
CMAKE_CXX_FLAGS_RELWITHDEBINFO and CMAKE_CXX_FLAGS_RELWITHDEBINFO are supposed to be identical in term of optimizations, it seems that none of the added cmake changes added by @maybegreat48  are actually doing anything and if they are it just means it's a cmake bug

2024-01-03 20:16 UTC, gir489returns commented
> How about we jst have Release, ReleaseWithDebInfo, Debug config options?
> 
> Release by default should have optimization enabled anyway, i'm not sure why all the things in the cmake file are needed

ReleaseWithDebInfo compiles it with debug info, which allows our crash logger to figure out the filename/line number where the crash happened. If we even allow people to compile without it, it would make those YimMenu.dll+0xworthless offsets that mean nothing in the log. We already have enough problems with that as-is. I vote no to this.

2024-01-03 20:19 UTC, xiaoxiao921 commented
For what it's worth the nightly already do exactly that, it compiles as Release instead of RelWithDebInfo

2024-01-03 20:20 UTC, gir489returns commented
> For what it's worth the nightly already do exactly that, it compiles as Release instead of RelWithDebInfo

Which is see column A:

>We already have enough problems with that as-is.

2024-01-06 18:59 UTC, gir489returns commented
@Yimura This PR is ready, as MBG has looked over the changes I did.

2024-01-06 19:31 UTC, xiaoxiao921 commented
> > For what it's worth the nightly already do exactly that, it compiles as Release instead of RelWithDebInfo
> 
> Which is see column A:
> 
> > We already have enough problems with that as-is.

Which makes it even more questionable? Why is the nightly still compiling as Release instead of DebInfo?
Also the CMake flags need to be cleaned, none of them are actually doing something, expect the /gs- one

2024-01-11 10:52 UTC, merged