Improved Aimbot
YimMenu/YimMenu pull request #2659
Opened 2024-01-28 04:32 UTC by navmodder

Fix aimbot when in vehicle
[Video](https://www.youtube.com/watch?v=8g1ZiXLJ4E0)

2024-01-28 11:08 UTC, lonelybud commented
any idea on why it aims down on ped when you are aiming from inside vehicle?

2024-01-28 16:07 UTC, gir489returns requested changes
The aimbot still is in a terribly unreliable state. https://youtu.be/gFlzA4MzRO4

In my video, you can see it still tries to grab people who are behind cover or are completely unshootable. It also fails to grab targets that are "too far" if I crank the distance up to 1000, it just aims over their head.

2024-01-28 16:07 UTC, gir489returns commented on src/backend/looped/weapons/aimbot.cpp
> +			if (PED::GET_PED_CONFIG_FLAG(self::ped, 78, 0))
Replace this with PLAYER::IS_PLAYER_FREE_AIMING

2024-01-28 16:07 UTC, gir489returns commented on src/backend/looped/weapons/aimbot.cpp
> +				if (!ENTITY::HAS_ENTITY_CLEAR_LOS_TO_ENTITY(self::ped, target_entity, 17))
Replace with HAS_ENTITY_CLEAR_LOS_TO_ENTITY_ADJUST_FOR_COVER.

2024-01-28 18:35 UTC, TheGreenBandit commented
I'm

2024-02-01 03:57 UTC, Sys0xdbg commented on src/backend/looped/weapons/aimbot.cpp
> +				float magnitude      = sqrtf(camera_target.x * camera_target.x + camera_target.y * camera_target.y
Yes, mistake because i used old commit.

2024-02-09 16:32 UTC, gir489returns commented
@navmodder What is the status of your work? I haven't been able to fix the issues I mentioned.

2024-02-11 00:00 UTC, Sys0xdbg commented
> @gir489returns 

I fixed the aiming issue, but that vehicle issue is still there. Tried adjusting the pitch for both vehicle and weapon, but no luck. Maybe we should just go back to the old way for now? My bad for pushing this broken thing.

2024-02-11 00:12 UTC, gir489returns commented
@navmodder Please take a look at the source code posted with #2701 and see if the math there makes yours better. Also, see if you can implement his visual checks, they seem to be superior, although it looks like he's just calling the native and not waiting like the documentation says to. If you can't get it working, I will properly port his code 1:1 over.

2024-03-05 17:16 UTC, gir489returns commented
@navmodder It has been 3 weeks. What is the status of porting the code from #2701 to your codebase?

2024-04-30 21:48 UTC, Yimura commented
No response from author and PR went stale.

2024-04-30 21:48 UTC, closed without merging