(Improvement) Request Model
YimMenu/YimMenu pull request #2669
Opened 2024-01-29 07:48 UTC by 99Anvar99

- We don't want to request models that does not exist! or invalid

2024-01-29 15:34 UTC, Yimura requested changes
Just some mixed indentations here and there as well as duplication of commonly used code.

### To Do:
 - [x] Move the code block that checks if a model is valid and then loads it to a helper function
 - [ ] Run clang-format to make the code that you submit uniform with the main code base.

2024-01-29 15:34 UTC, Yimura commented on src/util/entity.cpp
> +		else
Mixed indentation, run `clang-format -i src/**.hpp src/**.cpp` to fix.

2024-01-29 15:34 UTC, Yimura commented on src/util/ped.hpp
> +			}
Since this piece of code is being duplicated quite a bit, how about making it a general purpose helper function?

2024-01-29 15:38 UTC, 99Anvar99 commented on src/util/ped.hpp
> +			}
Sure thing.

2024-01-30 14:39 UTC, 99Anvar99 commented
My bad, i meant to say created helper for request model function not class.

2024-01-30 14:53 UTC, Yimura requested changes

2024-01-30 14:53 UTC, Yimura commented on src/util/entity.cpp
> +			}
`has_loaded` is never updated in this loop, might cause a deadlock.

2024-01-30 14:53 UTC, Yimura commented on src/util/entity.cpp
> +		return false;
Can be changed to `has_loaded`.

2024-01-30 14:53 UTC, Yimura commented on src/util/world_model.hpp
> +			memcpy(g_pointers->m_gta.m_world_model_spawn_bypass, backup.data(), patch_size);
I know this isn't your fault but could you update the patching of the `m_world_model_spawn_bypass` and make it into a `memory::byte_patch`?

Similarly to how it was implemented here:
https://github.com/YimMenu/YimMenu/blob/7efbee2e85ba2aee773e398cd9e66d54e640aca5/src/byte_patch_manager.cpp#L16

And here's an example usage:
https://github.com/YimMenu/YimMenu/blob/7efbee2e85ba2aee773e398cd9e66d54e640aca5/src/backend/looped/self/police.cpp#L19

2024-01-30 14:58 UTC, 99Anvar99 commented on src/util/world_model.hpp
> +			memcpy(g_pointers->m_gta.m_world_model_spawn_bypass, backup.data(), patch_size);
Yes, i will update it.

2024-01-31 09:46 UTC, Yimura approved these changes
Thanks for another PR fixing and improving some of the tech debt in YimMenu!

2024-01-31 09:47 UTC, merged