Refactor and fix send chat
YimMenu/YimMenu pull request #2864
Opened 2024-03-22 21:55 UTC by maybegreat48

* Refactors the chat send method
* Adds a lua function to send private chat messages (TODO implement in core YimMenu?)
* Team chats are now only sent to players on your team

Fixes #2861
Fixes #2783 
Fixes #1910

2024-03-22 22:00 UTC, Yimura requested changes
All looks good aside from a random indent I found.

2024-03-22 22:00 UTC, Yimura commented on src/views/network/view_network.cpp
> +				ImGui::SeparatorText("Bounty");
Random indent

2024-03-22 22:07 UTC, Yimura commented
Testing is required as @maybegreat48 has a broken GTA installation currently.

2024-03-22 22:09 UTC, gir489returns submitted a review, later dismissed
Pedantic changes. Not required.

2024-03-22 22:09 UTC, gir489returns commented on src/backend/reactions/interloper_reaction.cpp
> +			auto chat = std::format("{} {}", g.session.chat_output_prefix, g_translation_service.get_translation(m_announce_message));
This variable name makes no sense. It should be message or output or something.

2024-03-22 22:09 UTC, gir489returns commented on src/backend/reactions/interloper_reaction.cpp
> +			chat::send_message(chat);
Because here, lexically, it reads:

Chat interface. Send message: chat.

2024-03-22 22:09 UTC, gir489returns commented on src/backend/reactions/reaction.cpp
> +			chat::send_message(chat);
Ditto.

2024-03-22 22:37 UTC, gir489returns approved these changes
Looks good from a code standpoint. No idea if it actually works.

2024-03-22 22:38 UTC, maybegreat48 commented on src/views/network/view_network.cpp
> +				ImGui::SeparatorText("Bounty");
The code was originally indented using spaces but the file is supposed to use tab indents

2024-03-22 23:51 UTC, DayibBaba commented
> Looks good from a code standpoint. No idea if it actually works.

Nope. Crashes the instant a message is supposed to be sent such as an invalid vehicle model or invalid command.

2024-03-22 23:51 UTC, DayibBaba requested changes
Does not work. Crashes the instant a message is sent.

2024-03-23 04:03 UTC, gir489returns commented
> Does not work. Crashes the instant a message is sent. Log does not show anything of value. [cout.log](https://github.com/YimMenu/YimMenu/files/14729409/cout.log)

It seems to be crashing in chat.hpp line 197, probably because target is null. There is a bang check on it in the previous block. Should probably move it to the head of the function and just return if target is null.

2024-03-23 05:27 UTC, GreySideMM commented
> It seems to be crashing in chat.hpp line 197, probably because target is null. There is a bang check on it in the previous block. Should probably move it to the head of the function and just return if target is null.

Also further above: https://github.com/YimMenu/YimMenu/pull/2864/commits/879146cca642053b6549afe2fdd326e3f9edf654#diff-6805e0661392393a2391f0e1916f05d8b7c617a5d66960ce2a9e87deb3803a7aR191
As I understand it if target is set the function only should send a message to this specific player instead everyone. Not entirely sure how he wanted to handle is_team in that case. However:
Replacing `PLAYER::GET_PLAYER_TEAM(target->m_player_id)`
with `PLAYER::GET_PLAYER_TEAM(player.second->get_net_game_player()->m_player_id)`
should help there.
The lines 197 and also 200 still need attention. Not sure when that is supposed to be executed. Maybe a `if (draw && target)` ?

2024-03-23 09:48 UTC, DayibBaba commented
> > It seems to be crashing in chat.hpp line 197, probably because target is null. There is a bang check on it in the previous block. Should probably move it to the head of the function and just return if target is null.
> 
> Also further above: [879146c#diff-6805e0661392393a2391f0e1916f05d8b7c617a5d66960ce2a9e87deb3803a7aR191](https://github.com/YimMenu/YimMenu/commit/879146cca642053b6549afe2fdd326e3f9edf654#diff-6805e0661392393a2391f0e1916f05d8b7c617a5d66960ce2a9e87deb3803a7aR191) As I understand it if target is set the function only should send a message to this specific player instead everyone. Not entirely sure how he wanted to handle is_team in that case. However: Replacing `PLAYER::GET_PLAYER_TEAM(target->m_player_id)` with `PLAYER::GET_PLAYER_TEAM(player.second->get_net_game_player()->m_player_id)` should help there. The lines 197 and also 200 still need attention. Not sure when that is supposed to be executed. Maybe a `if (draw && target)` ?

We can make the netMessage send to simply a single person by hooking the sender and filtering on player message id.

2024-03-23 11:20 UTC, lonelybud commented
> It seems to be crashing in chat.hpp line 197, probably because target is null. There is a bang check on it in the previous block. Should probably move it to the head of the function and just return if target is null.

why we draw chat with target's name shouldn't be it sender's name?

2024-03-23 11:24 UTC, lonelybud commented
> Also further above 

correct it should be `(!is_team || PLAYER::GET_PLAYER_TEAM(player.second->id()) == PLAYER::GET_PLAYER_TEAM(self::id)))`

2024-03-23 13:20 UTC, lonelybud reviewed
these are little concerns. you are free to ignore

2024-03-23 13:20 UTC, lonelybud commented on src/util/chat.hpp
> +	inline void send_message(const std::string& message, CNetGamePlayer* target = nullptr, bool draw = true, bool is_team = false)
could use `player_ptr` instead of `CNetGamePlayer`.

2024-03-23 13:20 UTC, lonelybud commented on src/util/chat.hpp
> +				g_fiber_pool->queue_job([message, target, is_team] {
remove `target` from dependency list

2024-03-23 13:20 UTC, lonelybud commented on src/lua/bindings/network.cpp
> +			big::chat::send_message(msg, player->get_net_game_player());
could use `player_ptr` instead of `CNetGamePlayer`

2024-03-23 16:00 UTC, DayibBaba approved these changes
@Yimura We have decided to ignore the games logic for determining recipients. @maybegreat48 has added a function to determine who gets a chat message by our own logic. Should not differ much from how it originally works, barring any minor anomalies undiscovered as of now.

2024-03-23 16:26 UTC, gir489returns approved these changes

2024-03-23 16:37 UTC, Yimura approved these changes

2024-03-23 16:37 UTC, merged