fix(vehicle): fix repair not working after going in water
YimMenu/YimMenu pull request #2996
Opened 2024-04-29 09:48 UTC by xiaoxiao921

Closes #2995 

It's a bandaid fix but it works, there are multiple issues though. First person can't be used anymore in that specific vehicle, and can't be rentered. I tried messing with the vehicle flags and physical flags without any success sadly.

2024-04-29 13:34 UTC, gir489returns requested changes
I exclusively play in FPV, this fix is not acceptable to me as the original ticket submitter.

2024-04-30 15:35 UTC, gir489returns requested changes
Tested and working, but...

2024-04-30 15:35 UTC, gir489returns commented on src/util/vehicle.cpp
> +		VEHICLE::SET_VEHICLE_ENGINE_CAN_DEGRADE(veh, false);
This will make the vehicle semi-godmodded, the user did not ask for that.

2024-04-30 15:35 UTC, gir489returns commented on src/util/vehicle.cpp
> +		VEHICLE::SET_VEHICLE_ENGINE_ON(veh, true, true, false);
SET_VEHICLE_ENGINE_ON and SET_VEHICLE_NEEDS_TO_BE_HOTWIRED seems to be pointless together.

2024-04-30 15:35 UTC, gir489returns commented on src/util/vehicle.cpp
> +		VEHICLE::SET_VEHICLE_BODY_HEALTH(veh, 1000.f);
IIRC, SET_VEHICLE_FIXED does all of this? Check to confirm.

2024-04-30 22:06 UTC, rkwapisz commented
@xiaoxiao921 nailed it with the 0xD8 offset. Well done.
private int _oVState = 0xD8; // int 0:Player 1:NPC 2:Unused 3:Destroyed

Don't need anything else after that besides VEHICLE::SET_VEHICLE_FIXED(veh)

```
		auto cvehicle = (uint8_t*)g_pointers->m_gta.m_handle_to_ptr(veh);
		// fix vehicle being completly fucked after going into water.
		cvehicle[0xD8] &= ~(1 << 0);

		VEHICLE::SET_VEHICLE_FIXED(veh);
		VEHICLE::SET_VEHICLE_DIRT_LEVEL(veh, 0.f);
```

2024-04-30 23:07 UTC, rkwapisz commented
I think this concept could be easily expanded to repairs from any sort of destructive event, not just water. For example, from explosions.

If vehicle repair can be refactored to remember the player's last vehicle (like we can with GET_VEHICLE_PED_IS_IN(ped, lastVehicle = true), then the vehicle could be repaired even without the player having to physically be inside it. The bitmask could probably work for that case as well to recover the vehicle from any destroyed state, including a smouldering heap.

Then repair_engine_from_water could be renamed as something like repair_destroyed_vehicle. Would be great to be able to quickly repair a vehicle that was destroyed via explosion griefing without having to recall it from the PV list or call Mors.

2024-05-01 00:39 UTC, gir489returns approved these changes

2024-05-01 21:25 UTC, Yimura approved these changes

2024-05-01 21:25 UTC, merged