Finished 3 TODO`s
YimMenu/YimMenu pull request #3052
Opened 2024-05-04 17:28 UTC by timdev-ger

ImageButton - imgui.hpp
Image - imgui.hpp

system.hpp

2024-05-04 20:31 UTC, gir489returns approved these changes
System looks fine to me, xiao needs to approve the Lua changes.

2024-05-04 20:38 UTC, xiaoxiao921 submitted a review, later dismissed

2024-05-04 22:34 UTC, xiaoxiao921 commented
Approved the lua change but realized this wasnt even tested for compilation, tempting to just close this

2024-05-06 00:19 UTC, maybegreat48 commented on src/util/system.hpp
> +        std::ofstream file(file_path.get_path(), std::ios::out | std::ios::trunc);
This should stay disabled since there is no real crossmap anymore. The invoker now uses indices that map directly to translated hashes

2024-05-06 20:15 UTC, Yimura requested changes
Please take a look at the compiler output, there appears to be a missing include that's required to make this change working.

2024-05-07 23:04 UTC, maybegreat48 commented on src/util/system.hpp
> +        std::ofstream file(file_path.get_path(), std::ios::out | std::ios::trunc);
Just revert this and the code would compile

2024-05-09 08:37 UTC, timdev-ger commented
Backuped the system.hpp due an error.

As @maybegreat48 already said, there is no real crossmap anymore.
This was my mistake. It should compile now.

2024-05-09 13:27 UTC, Yimura commented
Did you compile this on your system before pushing? There are still compilation issues with the arguments being passed through.

2024-05-09 13:31 UTC, gir489returns commented
@Yimura These changes were done on GitHub. 

![image](https://github.com/YimMenu/YimMenu/assets/100792176/76cc49b5-bad6-44b1-89dc-6c7d946d877f)

You can also tell because the stupid GitHub editor demands that the EOL character change for the EOF.

2024-05-09 13:35 UTC, gir489returns commented
ImGui::Image and ImGui::ImageButton require passing a ImTextureID parameter, not just the "string" of the texture ID. This is quite an involved process to get working, and you can see on the ImGui documentation, this is probably something we want to remove from the Lua layer: https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-display-an-image-what-is-imtextureid-how-does-it-work

2024-05-09 13:35 UTC, closed without merging