Added filtering system to prepare_metric_for_sending.
YimMenu/YimMenu pull request #3139
Opened 2024-05-16 17:09 UTC by gir489returns

2024-05-16 17:09 UTC, gir489returns commented
![image](https://github.com/YimMenu/YimMenu/assets/100792176/ffb10583-fdf4-4abf-823e-55b78e7cf4d3)

2024-05-16 17:40 UTC, Rxann reviewed
I have noticed some metrics usually come in waves so this might spam the notifications, but this is a debug feature so that doesn't matter.

2024-05-16 17:50 UTC, gir489returns commented
> I have noticed some metrics usually come in waves so this might spam the notifications, but this is a debug feature so that doesn't matter.

![image](https://github.com/YimMenu/YimMenu/assets/100792176/f50c46c7-b3df-4797-abb5-a13289d04079)

2024-05-16 18:25 UTC, Yimura requested changes

2024-05-16 18:25 UTC, Yimura commented on src/hooks/info/prepare_metric_for_sending.cpp
> +			if (g.debug.logs.metric_logs == 1)
else if?

2024-05-16 18:25 UTC, Yimura commented on src/hooks/info/prepare_metric_for_sending.cpp
> +			}
Maybe notifications of these should be made optional.

2024-05-16 19:04 UTC, Yimura requested changes

2024-05-16 19:04 UTC, Yimura commented on src/core/settings.hpp
> +			bool warn_metric = true;
Idk, maybe the default should be false. I bet a bunch of people will whine about these popping up suddenly.

2024-05-16 19:33 UTC, gir489returns commented on src/hooks/info/prepare_metric_for_sending.cpp
> +		rage::json_serializer yim_serializer(metric_json_buffer, sizeof(metric_json_buffer));
![image](https://github.com/YimMenu/YimMenu/assets/100792176/133a3419-c710-47fe-a8ce-923e11fa097e)

2024-05-18 22:04 UTC, Yimura approved these changes

2024-05-18 22:04 UTC, merged