Added headlight and neon light options to LSC.
YimMenu/YimMenu pull request #332
Opened 2022-07-12 18:29 UTC by aa15032261

Also added [update feature for vehicle data.

2022-07-13 09:29 UTC, Yimura requested changes

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +			VEHICLE::SET_VEHICLE_TYRES_CAN_BURST(player_vehicle, !can_tires_burst);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +			VEHICLE::TOGGLE_VEHICLE_MOD(player_vehicle, MOD_TURBO, turbo);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +			VEHICLE::TOGGLE_VEHICLE_MOD(player_vehicle, MOD_TYRE_SMOKE, tiresmoke);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +							VEHICLE::SET_VEHICLE_MOD(player_vehicle, selected_slot, mod, true);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +			VEHICLE::TOGGLE_VEHICLE_MOD(player_vehicle, MOD_XENON_LIGHTS, xenon);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +			VEHICLE::SET_VEHICLE_NEON_LIGHT_ENABLED_(player_vehicle, NEON_LEFT, neon_left);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +			VEHICLE::SET_VEHICLE_NEON_LIGHT_ENABLED_(player_vehicle, NEON_RIGHT, neon_right);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +			VEHICLE::SET_VEHICLE_NEON_LIGHT_ENABLED_(player_vehicle, NEON_FRONT, neon_front);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +			VEHICLE::SET_VEHICLE_NEON_LIGHT_ENABLED_(player_vehicle, NEON_BACK, neon_back);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +							VEHICLE::SET_VEHICLE_TYRE_SMOKE_COLOR(player_vehicle, rgb[0], rgb[1], rgb[2]);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +							VEHICLE::SET_VEHICLE_NEON_LIGHTS_COLOUR_(player_vehicle, rgb[0], rgb[1], rgb[2]);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +					VEHICLE::SET_VEHICLE_NEON_LIGHTS_COLOUR_(player_vehicle, color_rgb[0], color_rgb[1], color_rgb[2]);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +						VEHICLE::SET_VEHICLE_COLOURS(player_vehicle, primary_color, secondary_color);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +							VEHICLE::SET_VEHICLE_COLOURS(player_vehicle, primary_color, secondary_color);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +							VEHICLE::SET_VEHICLE_COLOURS(player_vehicle, primary_color, secondary_color);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +							VEHICLE::SET_VEHICLE_COLOURS(player_vehicle, primary_color, secondary_color);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +							VEHICLE::SET_VEHICLE_EXTRA_COLOURS(player_vehicle, pearlescent, wheel_color);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +							VEHICLE::SET_VEHICLE_EXTRA_COLOURS(player_vehicle, pearlescent, wheel_color);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +							VEHICLE::SET_VEHICLE_INTERIOR_COLOR_(player_vehicle, interior_color);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +							VEHICLE::SET_VEHICLE_DASHBOARD_COLOR_(player_vehicle, dashboard_color);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 09:29 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_lsc.cpp
> +							VEHICLE::SET_VEHICLE_XENON_LIGHTS_COLOR_(player_vehicle, headlight_color);
Calling natives outside of script threads is detected.

Use the fiber pool please.

2022-07-13 12:49 UTC, Yimura approved these changes, later dismissed
Cool idea to use the `ETag` header as a reference point to decide when to update the local resource.

Haven't tested the code myself yet, but all looks good right now.

2022-07-13 14:53 UTC, aa15032261 commented
New changes:
- Introduced speed units to the program, which makes speed controls easier to use.
- Fixed issue #333 

![image](https://user-images.githubusercontent.com/22629802/178763723-1b9ead72-c081-486a-946f-ff548b90a424.png)

![image](https://user-images.githubusercontent.com/22629802/178764141-02ed7fd6-4089-4301-bb6c-c7f58cbebe06.png)

2022-07-13 15:17 UTC, howdoiusekeyboard commented
Great work! The bugs have been fixed.
Small observations:
1. Vehicle fly speed doesn't apply it don't stop is checked
2. In LSC in color options, Tire smake should be renamed to tire smoke and should be hidden/greyed out (like headlights in color option is greyed out if Headlight is greyed out in neon light options) if tiresmoke is not enabled in mod options

2022-07-13 15:34 UTC, aa15032261 commented
> Great work! The bugs have been fixed. Small observations:
> 
> 1. Vehicle fly speed doesn't apply it don't stop is checked
> 2. In LSC in color options, Tire smake should be renamed to tire smoke and should be hidden/greyed out (like headlights in color option is greyed out if Headlight is not enabled in neon light options) if tiresmoke is not enabled in mod options. Because doing otherwise crashes game

I've fixed item 2 in the latest commit. For item 1, when don't stop is enabled, the program applies the speed as force to the vehicle so the vehicle immediately reaches the max speed. I'm not sure if this behavior is intentional as I'm not the creator of this feature.

2022-07-13 16:45 UTC, howdoiusekeyboard commented
Yes, it has been fixed and works as intended
I found some bugs in LSC
1. 
![image](https://user-images.githubusercontent.com/90883505/178785407-0e45a095-9f23-4eec-b653-aa334de239db.png)
2. 
![image](https://user-images.githubusercontent.com/90883505/178785568-6f47f654-a9ca-4bbd-b624-c14bee7fdd00.png)
![image](https://user-images.githubusercontent.com/90883505/178786993-e341f952-dd54-461c-a377-db53cb53146d.png)

2022-07-13 17:08 UTC, aa15032261 commented
> Yes, it has been fixed and works as intended I found some bugs in LSC

Could you tell me how to reproduce these bugs?

2022-07-13 17:12 UTC, howdoiusekeyboard commented
> > Yes, it has been fixed and works as intended I found some bugs in LSC
> 
> Could you tell me how to reproduce these bugs?

Are you on discord? This is my id 尺ㄚᗪ乇尺爪ㄖ几Ҝ丨丨丨#9089
I can stream and show it to you there

2022-07-13 17:28 UTC, aa15032261 commented
> > > Yes, it has been fixed and works as intended I found some bugs in LSC
> > 
> > 
> > Could you tell me how to reproduce these bugs?
> 
> Are you on discord? This is my id 尺ㄚᗪ乇尺爪ㄖ几Ҝ丨丨丨#9089 I can stream and show it to you there

Nvm, I have figured it out and it is fixed in the latest commit.

2022-07-13 17:42 UTC, howdoiusekeyboard commented
> > > > Yes, it has been fixed and works as intended I found some bugs in LSC
> > > 
> > > 
> > > Could you tell me how to reproduce these bugs?
> > 
> > 
> > Are you on discord? This is my id 尺ㄚᗪ乇尺爪ㄖ几Ҝ丨丨丨#9089 I can stream and show it to you there
> 
> Nvm, I have figured it out and it is fixed in the latest commit.

Yes, a 3rd empty box bug with some mod options has been fixed and is much better but,
Front wheel option doesn't work and doesn't show the correct wheel (also didn't understand the naming)
1. I choose offroad in wheel type and it shows high end wheels set in front wheel and they don't apply, plus game crash

![image](https://user-images.githubusercontent.com/90883505/178796485-670d16ac-7137-4f01-85e2-8d12e9baa02e.png)


{Misc: Teleport to PV should be renamed to Teleport in PV}

2022-07-13 18:46 UTC, aa15032261 commented
> > > > > Yes, it has been fixed and works as intended I found some bugs in LSC
> > > > 
> > > > 
> > > > Could you tell me how to reproduce these bugs?
> > > 
> > > 
> > > Are you on discord? This is my id 尺ㄚᗪ乇尺爪ㄖ几Ҝ丨丨丨#9089 I can stream and show it to you there
> > 
> > 
> > Nvm, I have figured it out and it is fixed in the latest commit.
> 
> Yes, a 3rd empty box bug with some mod options has been fixed and is much better but, Front wheel option doesn't work and doesn't show the correct wheel (also didn't understand the naming)
> 
> 1. I choose offroad in wheel type and it shows high end wheels set in front wheel and they don't apply, plus game crash
> 
> ![image](https://user-images.githubusercontent.com/90883505/178796485-670d16ac-7137-4f01-85e2-8d12e9baa02e.png)
> 
> {Misc: Teleport to PV should be renamed to Teleport in PV}



> 


The issue should be fixed in the latest commit.

2022-07-13 21:50 UTC, Yimura commented
Tell me when  you're done with, though don't add any more features to this PR.

PR's are supposed to be a single feature or bug fix, if you want to fix bugs and do other things then you're supposed to make a PR for each.

2022-07-14 10:21 UTC, aa15032261 commented
> Tell me when you're done with, though don't add any more features to this PR.
> 
> PR's are supposed to be a single feature or bug fix, if you want to fix bugs and do other things then you're supposed to make a PR for each.

I'll keep that in mind, thanks! And yes, the code is now finalized.

2022-07-14 13:21 UTC, howdoiusekeyboard commented
Amazing work! I have tested thoroughly and I found no bugs

2022-07-14 14:16 UTC, Yimura approved these changes

2022-07-14 14:16 UTC, merged