Add more lsc colors
YimMenu/YimMenu pull request #3484
Opened 2024-07-31 19:34 UTC by V1RU513N

2024-07-31 19:58 UTC, gir489returns submitted a review, later dismissed

2024-07-31 23:53 UTC, gir489returns requested changes
See: https://gta.fandom.com/wiki/Vehicle_Customization_in_GTA_V/Respray_Colors#Classic

2024-07-31 23:53 UTC, gir489returns commented on src/core/data/lsc_types.hpp
> +	{COLOR_CLASSIC_ANTHRACITE_BLACK, "Anhracite Black"},
According to the GTA V wiki, this is supposed to be Anthracite Black, yes?

2024-08-01 00:00 UTC, V1RU513N commented on src/core/data/lsc_types.hpp
> +	{COLOR_CLASSIC_ANTHRACITE_BLACK, "Anhracite Black"},
Yes, the "color name" is “anthracite black” Anthracite grey would be the “technical name”, hence my confusion. I've chosen to stick to the “color name”.

https://docs.google.com/spreadsheets/d/e/2PACX-1vTa7yvIzGZRjK2cWS-jtkpD649KjV6vBR3cLjWQQ0JxCcLIotNGlxBMlqs_Z7c7lk8OQVUkGwgwdKqa/pubhtml

2024-08-01 00:08 UTC, gir489returns commented on src/core/data/lsc_types.hpp
> +	{COLOR_CLASSIC_ANTHRACITE_BLACK, "Anhracite Black"},
If you want to see how the game gets these values, you can use something like HUD::GET_FILENAME_FOR_AUDIO_CONVERSATION with the internal GXT strings to resolve it at runtime. This has the added benefit of using the game's translations for the colors.

If you need the GXT strings, carmod_shop should have them. I found a few using your spread sheet. func_1496 is Silver through Lime Green. func_1498 is Black through Frost White. func_1507 might be some kind of special color? Maybe pearlescent. It uses a couple of extra parameters, probably for the sheen percentage. It has Brushed Black Steel through Brushed Gold.

2024-08-01 14:49 UTC, gir489returns approved these changes

2024-08-02 08:08 UTC, Yimura approved these changes

2024-08-02 08:09 UTC, merged