Added ped model data.
YimMenu/YimMenu pull request #349
Opened 2022-07-17 15:11 UTC by aa15032261

![image](https://user-images.githubusercontent.com/22629802/179404641-ec108d77-de3c-48b0-a745-9b8d9f028325.png)

2022-07-17 15:44 UTC, howdoiusekeyboard commented
Can you add preview option in this?

2022-07-17 15:49 UTC, aa15032261 commented
> Can you add preview option in this?

Maybe in a future update

2022-07-17 15:53 UTC, howdoiusekeyboard commented
Add an option to be able to spawn appropriate ped types with weapons?

2022-07-17 17:22 UTC, aa15032261 commented
> Add an option to be able to spawn appropriate ped types with weapons?

Like body guards?

2022-07-17 20:09 UTC, Yimura requested changes

2022-07-17 20:09 UTC, Yimura commented on BigBaseV2/src/api/remote.hpp
> +			std::vector<std::string> headers = { "User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.2 (KHTML, like Gecko) Chrome/6.0" };
Use `constexpr std::vector<std::string>`  the value is never modified and the compiler can optimize this to not have to construct the vector each time.

2022-07-17 20:09 UTC, Yimura commented on BigBaseV2/src/main.cpp
> +					auto gta_data_service_instance = std::make_unique<gta_data_service>();
Call reset for this instance when unloading the DLL, see the other services that are beind called with .reset() further down.

2022-07-17 20:09 UTC, Yimura commented on BigBaseV2/src/services/gta_data/gta_data_service.hpp
> +	};
These classes could be moved to their own files, see the player service.

2022-07-17 21:29 UTC, howdoiusekeyboard commented
Can you filter ped type as per https://alloc8or.re/gta5/doc/enums/ePedType.txt

2022-07-17 21:31 UTC, aa15032261 commented
> Can you filter ped type as per https://alloc8or.re/gta5/doc/enums/ePedType.txt

There's a filter above model name textbox.

2022-07-17 21:36 UTC, howdoiusekeyboard commented
Yeah I see that, thats not what I meant
Ped types in this are filtered as: ['Animal', 'civmale', 'CIVFEMALE', 'COP', 'PLAYER_1', 'PLAYER_2', 'PLAYER_0', 'army', 'MEDIC', 'FIREMAN', 'Swat']
Its better to filter it as per ePedType https://alloc8or.re/gta5/doc/enums/ePedType.txt which is there in enums

2022-07-17 21:51 UTC, aa15032261 commented
> Yeah I see that, thats not what I meant Ped types in this are filtered as: ['Animal', 'civmale', 'CIVFEMALE', 'COP', 'PLAYER_1', 'PLAYER_2', 'PLAYER_0', 'army', 'MEDIC', 'FIREMAN', 'Swat'] Its better to filter it as per ePedType https://alloc8or.re/gta5/doc/enums/ePedType.txt which is there in enums

Some of the ped types aren't used by the models, at least according to the database. But I think I can add more categories in the future based on other info.

2022-07-19 10:18 UTC, Yimura approved these changes

2022-07-19 10:19 UTC, merged