Added clone current vehicle feature.
YimMenu/YimMenu pull request #351
Opened 2022-07-18 13:10 UTC by aa15032261

- Fixed some bugs in get_owned_mods_from_vehicle function.
- Fixed some weaponized PVs can't be cloned correctly.

![image](https://user-images.githubusercontent.com/22629802/179518399-2df51be2-43d6-4a29-8b30-40028cf564e0.png)

2022-07-19 10:21 UTC, Yimura submitted a review, later dismissed
Looks good to me, will have to test this later on.

2022-07-20 10:08 UTC, Yimura submitted a review, later dismissed

2022-07-21 00:18 UTC, mentolixite commented
This seems to cause a crash when spawning vehicles sometimes.

2022-07-21 02:44 UTC, aa15032261 commented
> This seems to cause a crash when spawning vehicles sometimes.

I’ll look into it

> This seems to cause a crash when spawning vehicles sometimes.

Clone pv or clone current?

2022-07-21 06:18 UTC, aa15032261 commented
> This seems to cause a crash when spawning vehicles sometimes.

Does the console show any error?

2022-07-21 06:41 UTC, aa15032261 commented
> This seems to cause a crash when spawning vehicles sometimes.
I've modified the code so it checks if the vehicle handle is valid before doing anything further. Hopefully it will fix the crash.

2022-07-23 16:25 UTC, Yimura requested changes
If you're still working on the PR you can change to a draft, that way I know that it isn't ready to review yet.

2022-07-23 16:25 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_pv.cpp
> +								LOG(WARNING) << "A====";
Debug log

2022-07-23 16:25 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_pv.cpp
> +									LOG(WARNING) << i << ": " << val;
Debug log

2022-07-23 16:25 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_pv.cpp
> +								LOG(WARNING) << "B====";
Debug log

2022-07-23 16:25 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_pv.cpp
> +									LOG(WARNING) << i << ": " << val;
Debug log

2022-07-23 16:25 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_pv.cpp
> +								LOG(WARNING) << "C====";
Debug log

2022-07-23 17:23 UTC, aa15032261 commented
@Yimura This PR is finalized. Sorry for the trouble.

2022-07-24 05:39 UTC, mentolixite commented
Appears to work fine, thanks!

2022-07-24 10:32 UTC, howdoiusekeyboard commented
I have found some bugs
1. After u preview current vehicle in the spawn tab, the other vehicles also have the same preview irrespective of model.
2. In the PV tab, after u preview a pv and hover off, and then hover on the same preview, the preview appears with vehicle mods not there. Exact bug with current vehicle in spawn tab
3. In your PV 's, if you have multiple builds of a model, with different mods on, and preview one of the build, and then try to preview the other build, the other build is previewed with the same mods on even though it has different mods.
4. I don't know if this is intentional but if u enabled spawn maxed in spawn, the vehicles aren't previewed with the respective mods. Same thing with spawn maxed in PV tab (after u enable spawn clone)
5. Clone doensn't get previewed with the PV plate if u have clone PV plate enabled
6. If you spawn a pv while keeping the preview, the preview gets the mods set on removed after it spawns

2022-07-24 12:31 UTC, aa15032261 commented
> I have found some bugs
> 
> 1. After u preview current vehicle in the spawn tab, the other vehicles also have the same preview irrespective of model.
> 2. In the PV tab, after u preview a pv and hover off, and then hover on the same preview, the preview appears with vehicle mods not there. Exact bug with current vehicle in spawn tab
> 3. In your PV 's, if you have multiple builds of a model, with different mods on, and preview one of the build, and then try to preview the other build, the other build is previewed with the same mods on even though it has different mods.
> 4. I don't know if this is intentional but if u enabled spawn maxed in spawn, the vehicles aren't previewed with the respective mods. Same thing with spawn maxed in PV tab (after u enable spawn clone)
> 5. Clone doensn't get previewed with the PV plate if u have clone PV plate enabled
> 6. If you spawn a pv while keeping the preview, the preview gets the mods set on removed after it spawns

Thanks for the feedback! I have fixed all issues except 5 in the latest commit. I think the plate number is not that important so I left that out. Please let me know if you find other issues.

2022-07-24 13:55 UTC, howdoiusekeyboard commented
Outstanding work man! Thanks

2022-07-27 15:47 UTC, aa15032261 commented
This PR also fixed issue 362.

2022-07-27 16:37 UTC, Yimura requested changes
Your vendor isn't up-to-date with master, you'll have to fix this as well before we can merge this.

2022-07-27 16:37 UTC, Yimura commented on BigBaseV2/src/views/vehicle/view_spawn.cpp
> +#include "services/players/player_service.hpp"
What's this include used for?

2022-07-27 17:18 UTC, aa15032261 commented on BigBaseV2/src/views/vehicle/view_spawn.cpp
> +#include "services/players/player_service.hpp"
It was used in the previous version and I forgot to remove it. Thanks for catching that.

2022-07-27 17:21 UTC, Yimura approved these changes
Alright looks good to me, will test it real quick.

2022-07-27 17:42 UTC, merged