Misc stuff
YimMenu/YimMenu pull request #3515
Opened 2024-08-04 14:26 UTC by Mr-X-GTA

Depends on https://github.com/Yimura/GTAV-Classes/pull/184

Fixes https://github.com/YimMenu/YimMenu/issues/3490
Fixes https://github.com/YimMenu/YimMenu/issues/3436
Fixes https://github.com/YimMenu/YimMenu/issues/3142

2024-08-04 15:29 UTC, Yahud1 commented on src/views/network/view_player_database.cpp
> -				ImGui::BeginDisabled(!joinable);
Maybe it's worth adding an input inside the player tracking which will be set to 45 seconds by default? so that there would be an opportunity to change the delay from 45 seconds to 1 for example. you can add a description that changing the value from 45 seconds to something else will be undesirable. because until 45 seconds pass we won't know whether this player is in the session or he is already in a mission or something else. and we will have to constantly return to singleplayer. this closes #3488

2024-08-04 15:41 UTC, Yimura submitted a review, later dismissed

2024-08-04 19:30 UTC, gir489returns requested changes

2024-08-04 19:30 UTC, gir489returns commented on src/views/network/view_player_database.cpp
> -				ImGui::EndDisabled();
#3488 is an invalid issue, please walk these changes back.

2024-08-05 00:50 UTC, gir489returns approved these changes

2024-08-05 07:15 UTC, merged