Input Method Editor
YimMenu/YimMenu pull request #3634
Opened 2024-08-29 12:43 UTC by Mr-X-GTA

Closes https://github.com/YimMenu/YimMenu/issues/3613

2024-08-29 13:03 UTC, gir489returns commented on src/util/input_method_editor.hpp
> +#pragma pack(pop)
Since this class is coming from GTA 5 itself, it belongs in the GTAV-Classes project.

2024-08-29 13:05 UTC, gir489returns requested changes

2024-08-29 13:05 UTC, gir489returns commented on src/util/input_method_editor.hpp
> +	inline void draw_input_method_editor()
Do these methods have to be inlined?

2024-08-29 13:05 UTC, gir489returns commented on src/util/input_method_editor.hpp
> +	inline void handle_ime_result()
Do these methods have to be inlined?

2024-08-29 13:05 UTC, gir489returns commented on src/pointers.cpp
> +                g_pointers->m_gta.m_ime = ptr.add(44).rip().sub(0x278 + 0x8).as<InputMethodEditor*>();
This is extremely unlikely to be consistent from version to version. I think finding a new signature for InputMethodEditor* would be more appropriate.

2024-08-29 13:16 UTC, Mr-X-GTA commented on src/pointers.cpp
> +                g_pointers->m_gta.m_ime = ptr.add(44).rip().sub(0x278 + 0x8).as<InputMethodEditor*>();
I looked in 1.54 and it's the same there. 0x278 is just the size of the class of which there are two instances for some reason but we only need the first one

2024-09-01 14:21 UTC, Mr-X-GTA commented on src/util/input_method_editor.hpp
> +	inline void draw_input_method_editor()
Yes

2024-09-01 14:24 UTC, gir489returns commented on src/util/input_method_editor.hpp
> +	inline void draw_input_method_editor()
They really don't as it's not doing anything in the function scope that has to be done once unrolled, and inline is a suggestion to the compiler, one it's probably ignoring. If it really did have to be inlined you'd be using __forceinline is bad.

2024-09-01 14:48 UTC, Mr-X-GTA commented on src/util/input_method_editor.hpp
> +	inline void draw_input_method_editor()
Yeah I mean they don't have to be inlined but the inline keyword is required to avoid multiple definition errors

2024-09-01 20:16 UTC, gir489returns approved these changes
Looks good on the surface, untested.

2024-09-01 21:05 UTC, Yimura approved these changes

2024-09-01 21:58 UTC, merged