Added weapons to gta_data_service.
YimMenu/YimMenu pull request #365
Opened 2022-07-28 06:48 UTC by aa15032261

2022-07-28 19:19 UTC, Yimura submitted a review, later dismissed
Looks good, haven't tested yet.

2022-07-29 09:42 UTC, karifeld reviewed
works good, one thing. it looks like youve added the `WEAPON_TACTICALRIFLE` (service carbine) to the `hash_blacklist` array by mistake.

that gun is unlockable in-game by normal means, i dont know if this is intentional or not

2022-07-29 10:41 UTC, aa15032261 commented
> works good, one thing. it looks like youve added the `WEAPON_TACTICALRIFLE` (service carbine) to the `hash_blacklist` array by mistake.
> 
> that gun is unlockable in-game by normal means, i dont know if this is intentional or not

It was a mistake. Thanks for spotting that! It is fixed in the latest commit.

2022-07-29 10:43 UTC, Yimura commented
@karifeld thanks for testing it.
@aa15032261 I'll merge it then after I've had one last look.

2022-07-29 10:48 UTC, Yimura requested changes

2022-07-29 10:48 UTC, Yimura commented on BigBaseV2/src/services/gta_data/gta_data_service.cpp
> +		}
redundant else as you've already returned (exit) out of the function in the if statement.

2022-07-29 10:48 UTC, Yimura commented on BigBaseV2/src/services/gta_data/weapon_item.cpp
> +		}
You can probably default the this->weapon_type = "NULL" and if the Category isn't null assign it.
```cpp
this->weapon_type = "NULL";
if (!item_json["Category"].is_null())
{
	this->weapon_type = item_json["Category"];
}
```

2022-07-29 11:22 UTC, Yimura approved these changes

2022-07-29 11:51 UTC, merged