Disable CMD executor if in-game keyboard is active
YimMenu/YimMenu pull request #3656
Opened 2024-09-03 15:46 UTC by ShinyWasabi

2024-09-03 15:52 UTC, gir489returns requested changes

2024-09-03 15:52 UTC, gir489returns commented on src/function_types.hpp
> +	using get_last_keyboard_state = int32_t (*)();
Seems stupid to return an int32_t when the function itself returns a KeyboardState.

2024-09-03 20:39 UTC, gir489returns approved these changes

2024-09-05 18:02 UTC, Yimura approved these changes

2024-09-05 18:02 UTC, merged