Merged auto_drive_to_waypoint and auto_drive_wander loops.
YimMenu/YimMenu pull request #369
Opened 2022-07-29 11:47 UTC by aa15032261

2022-07-29 12:01 UTC, howdoiusekeyboard commented
Would be cool if you could add auto_drive_to_objective

2022-07-29 12:03 UTC, aa15032261 commented
> Would be cool if you could add auto_drive_to_objective

Thanks for the suggestion. I’ll add that in.

2022-07-29 14:44 UTC, aa15032261 commented
> Would be cool if you could add auto_drive_to_objective

The feature is implemented in the latest commit.

2022-07-29 20:15 UTC, Yimura requested changes

2022-07-29 20:15 UTC, Yimura commented on BigBaseV2/src/util/blip.hpp
> +		);
Script yield gone?

2022-07-29 20:15 UTC, Yimura commented on BigBaseV2/src/backend/looped/vehicle/auto_drive.cpp
> +			bool is_waypoint_exist = false;
`does_waypoint_exist` sounds better.

2022-07-30 16:13 UTC, Yimura approved these changes

2022-07-30 16:52 UTC, Yimura commented
Seems to work, didn't really test in-depth.

2022-07-30 16:53 UTC, merged