vehicles, peds, weapons local cache
YimMenu/YimMenu pull request #457
Opened 2022-09-27 18:45 UTC by xiaoxiao921

Create a local cache once per game update.
The only issue currently is that if the user inject in SP and go to MP a crash will trigger because of some rpf file that got mounted twice is needed for the loading, its pretty meh but i'm not sure how to fix it, the fidevice system is a huge can of worm in itself and i'm out of energy for this right now. Atleast this crash will trigger "only" once per update because once the cache is done for the current update it just query the json files from disk

2022-09-27 19:14 UTC, Yimura commented
I'm sure if we'd look at how to fix that crash we can figure it out.

2022-09-28 16:21 UTC, Yimura requested changes
Looks good, making these comments just to keep track of them so don't worry about the TODO comment.

I will jump into the PR myself as well to take a look at what I can do.

2022-09-28 16:21 UTC, Yimura commented on BigBaseV2/src/services/gta_data/gta_data_service.cpp
> +							veh["Price"] = -1; // todo: how DurtyFree generate it?
CHandlingData has this information I believe.

https://github.com/Yimura/GTAV-Classes/blob/1da236c3c6ca5586dc9e1069dde1fbfd49641882/vehicle/CHandlingData.hpp#L74

2022-09-28 16:21 UTC, Yimura commented on BigBaseV2/src/services/gta_data/gta_data_service.cpp
> +							veh["ClassId"] = 0; // todo: how DurtyFree generate it?
CVehicleModelInfo probably.

https://github.com/Yimura/GTAV-Classes/blob/1da236c3c6ca5586dc9e1069dde1fbfd49641882/vehicle/CVehicleModelInfo.hpp#L48

2022-09-28 16:21 UTC, Yimura commented on BigBaseV2/src/services/gta_data/gta_data_service.cpp
> +							veh["DlcName"] = "TODO"; // todo: how DurtyFree generate it?
Unsure I'd like to know as well.

2022-09-28 16:21 UTC, Yimura commented on BigBaseV2/src/services/gta_data/gta_data_service.cpp
> +							ped["MovementClipSets"] = nullptr; // todo
To Do.

2022-09-28 16:29 UTC, SkiddyToast commented
I'd also recommend moving the `fiDevice` and `GXT2` related classes into the GTAV-Classes repo.

2022-09-28 16:30 UTC, Yimura commented
Yeah, right now for simplicity of implementing it I'm going to merge the classes into the repo and at later moment we can move them to the other repo.

2022-09-30 11:09 UTC, maybegreat48 commented
Haven't tested this but loading MP DLC through `DLC::ON_ENTER_MP` beforehand may stop the crash

2022-09-30 11:19 UTC, Yimura commented
Will test that afterwards. Right now I'm busy revamping the whole GTA Data service class. Throwing away the need for JSON files and instead store it binary.

I'm so glad this thing works though as is.

2022-10-04 23:07 UTC, Yimura commented
99% finished

Here and there can be optimised some more where we're copying vectors over where we might get away by moving the memory.
I crashed while previewing the vehicles, didn't check which one I crashed one (probably next-gen that we're not filtering out).

Current structure uses the following binary header format:
|Order|Field Name|Field Size (bytes)|Type|
|--|--|--|--|
|1|cache version|4|`uint32`|
|2|game build|4|`uint32`|
|3|online version|4|`float`|
|4|data size|8|`uint64`|
|5|data| / | `any` |

2022-10-05 14:13 UTC, Yimura commented
Seems the next-gen vehicles are causing crashes again; I have no idea from where I need to parse the bones of a vehicle model.

These are the current methods of checking for invalid vehicles, I checked handling.meta for monetaryValue but that one never seemed to be 0:
https://github.com/YimMenu/YimMenu/blob/d01afda8d360baa527099d8952eb745cf75d5dee/BigBaseV2/src/services/gta_data/gta_data_service.cpp#L238-L240

Edit:
I've found the arbitergt.ytf file which contains a stub bone it seems.
![image](https://user-images.githubusercontent.com/24669514/194083797-94dc4587-4fe9-46c7-b699-51fb6258a157.png)

2022-10-18 22:07 UTC, Yimura commented
Should be ready to merge, @xiaoxiao921 tell me if you see anything.

2022-10-18 22:11 UTC, GeopJr commented
Could you bump pugixml to HEAD (`86c91051541d18a0d24b837a866cf0306fc8db1a`)? (it had some bug fixes since `521b2cd`)

2022-10-18 22:19 UTC, Yimura approved these changes

2022-10-18 22:20 UTC, Yimura commented
Going to merge soon, I want to retire the proxy server in the next 2 weeks.

2022-10-18 22:30 UTC, merged