feat(CMsgPackedEvents): Improve received_event and remove the hook
YimMenu/YimMenu pull request #520
Opened 2022-10-26 02:37 UTC by Faint0002

Just something I reversed and thought it'd be nice to have one less hook in the case they decide to int check received_event.
Code works fine, was tested in game. See below

Screenshot of log while using modified received_event:
https://uploadi.ng/L4z6aTBy

2022-10-26 18:20 UTC, Yimura approved these changes

2022-10-26 18:25 UTC, Yimura requested changes
Something seems wrong when passing data received_event => script_event_handler or possibly even earlier in the callstack from CMsgPackedEvents.

No data appears to be passed to the script_event_handler.
```
[20:22:24][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:24][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Corrupxi0n Event Type: TSE sender mismatch
[20:22:24][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:24][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: NicuPaleru99 Event Type: TSE sender mismatch
[20:22:24][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:24][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: MrBezbaw911 Event Type: TSE sender mismatch
[20:22:25][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:25][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Xachserr__ Event Type: TSE sender mismatch
[20:22:28][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:28][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Nazar_kydelya Event Type: TSE sender mismatch
[20:22:29][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:29][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: BigFreddyKrueger Event Type: TSE sender mismatch
[20:22:31][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:31][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:31][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:31][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:31][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:31][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:31][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:31][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:31][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:31][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:33][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:33][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: miltiad7 Event Type: TSE sender mismatch
[20:22:33][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:33][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: miltiad7 Event Type: TSE sender mismatch
[20:22:33][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:33][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: LED4iK_Ukraine Event Type: TSE sender mismatch
[20:22:33][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:33][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: dyti7_ Event Type: TSE sender mismatch
[20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: dyti7_ Event Type: TSE sender mismatch
[20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: StarKitSuny Event Type: TSE sender mismatch
[20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: miltiad7 Event Type: TSE sender mismatch
[20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Nazar_kydelya Event Type: TSE sender mismatch
[20:22:36][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:36][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:37][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:37][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: StarKitSuny Event Type: TSE sender mismatch
[20:22:37][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:37][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:37][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:37][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
[20:22:39][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:39][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: LED4iK_Ukraine Event Type: TSE sender mismatch
[20:22:39][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:39][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: LED4iK_Ukraine Event Type: TSE sender mismatch
[20:22:40][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:40][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: LED4iK_Ukraine Event Type: TSE sender mismatch
[20:22:41][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:41][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: dyti7_ Event Type: TSE sender mismatch
[20:22:42][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:42][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Corrupxi0n Event Type: TSE sender mismatch
[20:22:42][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:42][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: StarKitSuny Event Type: TSE sender mismatch
[20:22:42][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:42][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: StarKitSuny Event Type: TSE sender mismatch
[20:22:42][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:42][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: StarKitSuny Event Type: TSE sender mismatch
[20:22:43][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:43][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Nazar_kydelya Event Type: TSE sender mismatch
[20:22:44][INFO/script_event_handler.cpp:29]: Hash = 0
[20:22:44][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Nazar_kyde [...]

2022-10-27 00:09 UTC, Faint0002 commented
> Something seems wrong when passing data received_event => script_event_handler or possibly even earlier in the callstack from CMsgPackedEvents.
> 
> No data appears to be passed to the script_event_handler.
> 
> ```
> [20:22:24][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:24][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Corrupxi0n Event Type: TSE sender mismatch
> [20:22:24][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:24][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: NicuPaleru99 Event Type: TSE sender mismatch
> [20:22:24][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:24][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: MrBezbaw911 Event Type: TSE sender mismatch
> [20:22:25][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:25][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Xachserr__ Event Type: TSE sender mismatch
> [20:22:28][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:28][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Nazar_kydelya Event Type: TSE sender mismatch
> [20:22:29][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:29][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: BigFreddyKrueger Event Type: TSE sender mismatch
> [20:22:31][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:31][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:31][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:31][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:31][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:31][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:31][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:31][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:31][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:31][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:33][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:33][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: miltiad7 Event Type: TSE sender mismatch
> [20:22:33][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:33][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: miltiad7 Event Type: TSE sender mismatch
> [20:22:33][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:33][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: LED4iK_Ukraine Event Type: TSE sender mismatch
> [20:22:33][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:33][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: dyti7_ Event Type: TSE sender mismatch
> [20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:34][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:34][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: dyti7_ Event Type: TSE sender mismatch
> [20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: StarKitSuny Event Type: TSE sender mismatch
> [20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: miltiad7 Event Type: TSE sender mismatch
> [20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:35][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:35][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Nazar_kydelya Event Type: TSE sender mismatch
> [20:22:36][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:36][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:37][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:37][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: StarKitSuny Event Type: TSE sender mismatch
> [20:22:37][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:37][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:37][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:37][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Sifouu15791 Event Type: TSE sender mismatch
> [20:22:39][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:39][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: LED4iK_Ukraine Event Type: TSE sender mismatch
> [20:22:39][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:39][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: LED4iK_Ukraine Event Type: TSE sender mismatch
> [20:22:40][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:40][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: LED4iK_Ukraine Event Type: TSE sender mismatch
> [20:22:41][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:41][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: dyti7_ Event Type: TSE sender mismatch
> [20:22:42][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:42][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: Corrupxi0n Event Type: TSE sender mismatch
> [20:22:42][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:42][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: StarKitSuny Event Type: TSE sender mismatch
> [20:22:42][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:42][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: StarKitSuny Event Type: TSE sender mismatch
> [20:22:42][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:42][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: StarKitSuny Event Type: TSE sender mismatch
> [20:22:43][INFO/script_event_handler.cpp:29]: Hash = 0
> [20:22:43][WARNING/script_event_handler.cpp:9]: BLOCKED_SCRIPT_EVENT From: [...]

2022-10-27 01:50 UTC, pelecanidae commented
Yeah, unfortunately I can't give you actual feedback because I don't remember the exact issue/have my codebase handy, but there's a bug in the bitbuffer read logic. 💀

2022-10-29 19:48 UTC, Faint0002 commented
PR is unneeded.

2022-10-29 19:48 UTC, closed without merging