Added Infinite ammo & clip.
YimMenu/YimMenu pull request #55
Opened 2022-02-09 04:13 UTC by xM4ddy

Resolved Issue #53.

2022-02-09 10:33 UTC, Yimura commented
Might also be cool to take a look at doing this in memory, this is something for later though since I don't think the offsets in the GTAV Classes have support for this yet.

2022-02-09 14:49 UTC, ThatKakiGuy approved these changes

2022-02-09 15:04 UTC, Yimura requested changes

2022-02-09 15:04 UTC, Yimura commented on BigBaseV2/src/backend/looped/weapons/infinite_ammo.cpp
> +#include "util/notify.hpp"
Remove unused includes.

2022-02-09 15:04 UTC, Yimura commented on BigBaseV2/src/backend/looped/weapons/infinite_mag.cpp
> +#include "util/notify.hpp"
Remove unused includes.

2022-02-09 15:04 UTC, Yimura commented on BigBaseV2/src/core/globals.hpp
> +					{ "infinite_mag", (int)this->weapons.infinite_mag }
Why cast this to int?
Boolean is a native type supported by json.

2022-02-12 10:09 UTC, Yimura commented
@xM4ddy please review the requested changes, otherwise I can't merge this in YimMenu.

2022-02-13 22:48 UTC, Yimura commented on BigBaseV2/src/core/globals.hpp
> +		this->weapons.custom_weapon = j["weapons"]["infinite_mag"];
You're assigning infinite_ammo and infinite_mag settings to the custom_weapon setting, this will not work.

2022-02-13 22:48 UTC, Yimura requested changes

2022-02-13 22:48 UTC, Yimura commented on BigBaseV2/src/core/globals.hpp
> +		this->weapons.custom_weapon = j["weapons"]["infinite_mag"];
You're assigning infinite_ammo and infinite_mag settings to the custom_weapon setting, this will not work.

2022-02-13 22:54 UTC, Yimura approved these changes

2022-02-13 22:56 UTC, Yimura commented
@xM4ddy I've fixed the code this time but next time make sure you submit a fully working code base, you just made sure it compiled without actually fixing any problems. Doesn't appear either that you tried to think about what you did wrong and instead just made the compiler happy.

2022-02-13 22:56 UTC, merged