feat: MinGW compatible build.
YimMenu/YimMenu pull request #562
Opened 2022-11-09 04:28 UTC by tupoy-ya

# Reason
MSVC is windows only and using a VM to compile this menu every time you change something isn't nice.

Related:
+ https://github.com/YimMenu/YimMenu/pull/342
+ https://github.com/YimMenu/YimMenu/issues/334

# Additional context
- [x] Compiles on MinGW
- [x] Compiles on MSVC
- [x] Runs
- [x] CI
- [ ] Fix virtual function crash
- [ ] Maybe make it link dynamically?
- [ ] Merge https://github.com/YimMenu/g3log/pull/4

P.s: Some commits from my cmake PR are visible here sorry about that.

2022-11-10 04:39 UTC, tupoy-ya commented
Ubuntu uses `x86_64-w64-mingw32-gcc` 10-win32 20220324
while arch uses `x86_64-w64-mingw32-gcc` 12.2.0.
I don't really know if i want to port YimMenu to gcc 10.

Also ubuntu doesn't have `uasm` assembler in their repos.

2022-11-10 07:56 UTC, GeopJr commented on .github/workflows/ci.yml
> +            submodules: recursive
No longer needed (since there's no submodules).

2022-11-10 08:01 UTC, GeopJr requested changes
We should probably *not* target ubuntu and instead target alpine docker.
Here's an example (working) Dockerfile:

```Dockerfile
FROM alpine:edge
RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add glslang git mingw-w64-gcc cmake uasm meson
RUN git clone https://github.com/tupoy-ya/TupoyeMenu/ -b feat-mingw-build --depth=1 YimMenu

WORKDIR YimMenu
RUN cmake -DVERSION=1.3.4 -DCMAKE_BUILD_TYPE:STRING=Release -S. -Bbuild -G Ninja
RUN cmake --build build --config Release
RUN sha256sum build/libYimMenu.dll
```

IMO we should publish a YimMenu Docker image which will then be used for devcontainer and the mingw actions: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

cc: @Yimura

2022-11-12 10:20 UTC, tupoy-ya commented
After compiling with clang i get this weird result:
```
[12:28:34][DEBUG/send_metric.cpp:46]: METRIC: 
[12:28:34][INFO/send_metric.cpp:47]: PN4rage8rlMetricE: 0x20202FB860CA12AD
```
It doesn't crash but it doesn't work either.
Second line is just:
```cpp
LOG(INFO) << typeid(metric).name() << ": " << HEX_TO_UPPER(typeid(metric).hash_code()); //Use this to get hashes for each node
```
From `received_clone_sync.cpp`

2022-11-12 11:25 UTC, xiaoxiao921 commented
I could be wrong but I think you can forget using any compiler other than msvc due to vtable and rtti being not standardized and being compiler impl specific

2022-11-12 12:41 UTC, xiaoxiao921 commented
fms-compatibility flag and https://clang.llvm.org/docs/MSVCCompatibility.html is worth looking at

2022-11-12 12:43 UTC, tupoy-ya commented
It fails to build with it but if it gets build then maybe it will work.

2022-11-12 14:04 UTC, tupoy-ya commented
Ok after i added `-fms-compatibility` it just crashes.
And it still doesn't use MSVC name mangling
`_ZN3big10log_metricEPN4rage8rlMetricE`
<details>
  <summary>Crash log</summary>

```
[18:52:02][INFO/main.cpp:62]: Yim's Menu Initializing
[18:52:03][INFO/globals.hpp:1135]: Updating settings.
[18:52:03][INFO/main.cpp:65]: Settings Loaded.
Found 'SCREEN_RESOLUTION' GTA5.exe+0x16C157
Found 'RC' GTA5.exe+0x13C825C
Found 'MWL' GTA5.exe+0x5D45BB
Found 'GS' GTA5.exe+0x2BF068
Found 'ISA' GTA5.exe+0xEC43
Found 'PF' GTA5.exe+0x728E48
Found 'NPM' GTA5.exe+0x1076C6C
Found 'NH' GTA5.exe+0x15C2131
Found 'FV' GTA5.exe+0x15BF0E0
Found 'ST' GTA5.exe+0x15C2087
Found 'SP' GTA5.exe+0xA3B7CD
Found 'SG' GTA5.exe+0x15C19D8
Found 'CGSHM' GTA5.exe+0x15C6B69
Found 'S' GTA5.exe+0x1345189
Found 'MSB' GTA5.exe+0xA395B2
Found 'WMSB' GTA5.exe+0xCDCE99
Found 'NRF' GTA5.exe+0x4A0C32
Found 'GTS' GTA5.exe+0x15C1BA0
Found 'TK' GTA5.exe+0xA3F898
Found 'TSE' GTA5.exe+0xD6A848
Found 'REH' GTA5.exe+0x167940C
Found 'SEA' GTA5.exe+0x1664215
Found 'RBWD' GTA5.exe+0x109D111
Found 'RBA' GTA5.exe+0x12E353C
Found 'RBS' GTA5.exe+0x1170CFC
Found 'RBB' GTA5.exe+0x11278C7
Found 'WBD' GTA5.exe+0x1127E10
Found 'WBQ' GTA5.exe+0x12EB2EC
Found 'WBI64' GTA5.exe+0x1174381
Found 'WBI32' GTA5.exe+0x1173253
Found 'WBB' GTA5.exe+0x1172DD8
Found 'WBA' GTA5.exe+0x1663FD6
Found 'WPGSDN' GTA5.exe+0x10CCE94
Found 'RCOE-Patch' GTA5.exe+0xCCC264
Found 'RI' GTA5.exe+0x1E9C
Found 'PTH' GTA5.exe+0x15C6625
Found 'GSH' GTA5.exe+0x15C7AF4
Found 'BE' GTA5.exe+0xA64FBB
Found 'SNITL' GTA5.exe+0x13BC4BA
Found 'CNOM' GTA5.exe+0xB108C4
Found 'NPMI' GTA5.exe+0x10D78E7
Found 'NPMS' GTA5.exe+0x110BB3A
Found 'FR' GTA5.exe+0xCC8F38
Found 'GSCFWC' GTA5.exe+0xA3A934
Found 'GGCC' GTA5.exe+0xA6F1F2
Found 'GPR' GTA5.exe+0x118F304
Found 'WPGDN' GTA5.exe+0x10CD9B0
Found 'NGO' GTA5.exe+0x72705C
Found 'RNM' GTA5.exe+0x14035FD
Found 'GNED' GTA5.exe+0x19D32F8
Found 'API' GTA5.exe+0x167F4D8
Found 'RCS/GSTFT/GNOFP/GNO/GSTI' GTA5.exe+0x10E2E61
Found 'RBIST' GTA5.exe+0x10E202C
Found 'MHT' GTA5.exe+0xAF80
Found 'GLT' GTA5.exe+0xD86917
Found 'MCF' GTA5.exe+0x163D5E2
Found 'N' GTA5.exe+0x10448B1
Found 'RENC' GTA5.exe+0x142900A
Found 'FDGD' GTA5.exe+0x12CF527
Found 'FDS' GTA5.exe+0x12D2084
Found 'FPFC' GTA5.exe+0x12CBEB2
Found 'FPFOA' GTA5.exe+0x12D0DA0
Found 'FPFM' GTA5.exe+0x12D22FA
Found 'FPFUM' GTA5.exe+0x69E6C7
Found 'GVOV' GTA5.exe+0x2E0438
Found 'IMCD' GTA5.exe+0x53443D
Found 'FMFS' GTA5.exe+0x13BB9D8
Found 'SGSBGH' GTA5.exe+0x439B89
Found 'JSBI' GTA5.exe+0x114EA64
[18:52:04][INFO/main.cpp:68]: Pointers initialized.
[18:52:04][WARNING/main.cpp:176]: std::bad_alloc
[18:52:04][INFO/main.cpp:179]: Farewell!
```
</details>

2022-11-12 14:17 UTC, xiaoxiao921 commented
For the mangling we have it implemented as a constexpr so maybe we can use that instead? For the bad alloc no idea but it's worth removing the try catch so that you can just let g3log give the exact faulty line

2022-11-12 14:20 UTC, tupoy-ya commented
Turns out this crash had nothing to do with MinGW build it's just @Yimura adding windows only fonts again.

2022-11-12 14:21 UTC, tupoy-ya commented
Removing this new font fixes the crash but everything else is still the same.
```
[19:18:41][DEBUG/send_metric.cpp:46]: METRIC: 
[19:18:41][INFO/send_metric.cpp:47]: PN4rage8rlMetricE: 0x20202FB860CA12AD
```

2022-11-18 07:35 UTC, tupoy-ya commented
If someone just wants to compile on linux i suggest looking into [msvc-wine](https://github.com/mstorsjo/msvc-wine)(requires ubuntu 20 chroot on Arch, at least for me) because working `GCC || clang` build seems impossible for now.

2022-11-20 19:40 UTC, avail commented
have you never heard of `premake5 gmake2`? what bullshit is this.

2022-11-20 19:41 UTC, Yimura commented
> have you never heard of `premake5 gmake2`? what bullshit is this.

We have, please see #342

2022-11-22 06:11 UTC, Kakiking commented
>  Maybe make it link dynamically?
In my experience linking dynamically generally broke things with wine, because wine doesn't find the stdc++ libraries for some reason.
I personally don't see any benefits to linking dynamically here, so why bother?

2022-11-22 06:16 UTC, Kakiking commented
I'd love to be able to use YimMenu on Linux though. I'll definitely look into it once I can get Social Club to stop crashing with wine. If anyone has experience with these kind of Problems feel free to send me an email ^^

2022-12-20 19:19 UTC, tupoy-ya reviewed
Well it mostly loads into online now (somehow), but crashes at `Freemode Swoop Down | 27`

```
Found 'SCREEN_RESOLUTION' GTA5.exe+0x169D7F
Found 'RC' GTA5.exe+0x13EA96C
[00:04:04][INFO/main.cpp:64]: Yim's Menu Initializing
[00:04:04][INFO/main.cpp:65]: Git Info
	Branch:	feat-mingw-build
	Hash:	5b8193edd8960c4236998c8457374da405d1c6f7-dirty
	Date:	Mon Nov 14 15:10:33 2022
[00:04:04][INFO/main.cpp:68]: Thread pool initialized.
[00:04:04][INFO/main.cpp:72]: Settings Loaded.
[00:04:04][DEBUG/thread_pool.cpp:21]: Allocating 4 threads in thread pool.
Found 'MWL' GTA5.exe+0x5D8FDB
Found 'GS' GTA5.exe+0x2C0794
Found 'ISA' GTA5.exe+0xEE07
Found 'PF' GTA5.exe+0x72DCE8
Found 'NPM' GTA5.exe+0x1095C28
Found 'NH' GTA5.exe+0x15E5E75
Found 'FV' GTA5.exe+0x15E2D88
Found 'ST' GTA5.exe+0x15E5DCB
Found 'SP' GTA5.exe+0xA42ED9
Found 'SG' GTA5.exe+0x15E571C
Found 'CGSHM' GTA5.exe+0x15EA7E9
Found 'S' GTA5.exe+0x136644D
Found 'WMSB' GTA5.exe+0xCEDBD5
Found 'NRF' GTA5.exe+0x11D31C
Found 'GTS' GTA5.exe+0x15E58E4
Found 'TK' GTA5.exe+0xA46F4C
Found 'TSE' GTA5.exe+0xD80C7C
Found 'REH' GTA5.exe+0x169C980
Found 'SEA' GTA5.exe+0x16870C1
Found 'RBWD' GTA5.exe+0x1144E15
Found 'RBA' GTA5.exe+0x13048C8
Found 'RBS' GTA5.exe+0x11922B0
Found 'RBB' GTA5.exe+0x1148017
Found 'WBD' GTA5.exe+0x141381C
Found 'WBQ' GTA5.exe+0x130C678
Found 'WBI64' GTA5.exe+0x1195965
Found 'WBI32' GTA5.exe+0x1194837
Found 'WBB' GTA5.exe+0x1194338
Found 'WBA' GTA5.exe+0x1686E82
Found 'WPGSDN' GTA5.exe+0x10ED2A8
Found 'RCOE-Patch' GTA5.exe+0xCDCE88
Found 'RI' GTA5.exe+0x20B0
Found 'PTH' GTA5.exe+0x15EA2A5
Found 'GSH' GTA5.exe+0x15EB774
Found 'BE' GTA5.exe+0xA6C934
Found 'SNITL' GTA5.exe+0x13DE92E
Found 'CNOM' GTA5.exe+0xB195CC
Found 'NPMI' GTA5.exe+0x10F7CE3
Found 'NPMS' GTA5.exe+0x112C0C6
Found 'FR' GTA5.exe+0xCD9AA4
Found 'GSCFWC' GTA5.exe+0xA42044
Found 'GGCC' GTA5.exe+0xA76C62
Found 'GPR' GTA5.exe+0x11B06A0
Found 'WPGDN' GTA5.exe+0x10EDDC4
Found 'RNM' GTA5.exe+0x1426BDD
Found 'GNED' GTA5.exe+0x19F2770
Found 'API' GTA5.exe+0x16A2B10
Found 'RCC' GTA5.exe+0x11022B4
Found 'CAD' GTA5.exe+0x1102B52
Found 'RCS/GSTFT/GNOFP/GNO/GSTI' GTA5.exe+0x110326D
Found 'RBIST' GTA5.exe+0x1102434
Found 'MHT' GTA5.exe+0xB142
Found 'GLT' GTA5.exe+0xDA11BF
Found 'MCF' GTA5.exe+0x16604F2
Found 'N' GTA5.exe+0x1061525
Found 'RENC' GTA5.exe+0x144C60E
Found 'FDGD' GTA5.exe+0x12F824B
Found 'FDS' GTA5.exe+0x12FADA8
Found 'FPFC' GTA5.exe+0x12F4C22
Found 'FPFOA' GTA5.exe+0x12F9AB4
Found 'FPFM' GTA5.exe+0x12FB01E
Found 'FPFUM' GTA5.exe+0x6A301F
Found 'GVOV' GTA5.exe+0x2E19C4
Found 'IMCD' GTA5.exe+0x53894D
Found 'SCP' GTA5.exe+0x2EEDEC
Found 'SCM' GTA5.exe+0x10A7A45
Found 'SGSBGH' GTA5.exe+0x43D2E9
Found 'SGSBGH' GTA5.exe+0x13F0F26
Found 'JSBI' GTA5.exe+0x116F944
Found 'INT' GTA5.exe+0x15E24AE
Found 'VM' GTA5.exe+0x15E5726
Found 'GU' GTA5.exe+0x140F832
Found 'HT' GTA5.exe+0x13E411D
Found 'PGI' GTA5.exe+0x13FFD4C
Found 'PIGI' GTA5.exe+0x10A18BF
Found 'C' GTA5.exe+0xCDBAF7
Found 'SDEGSDN' GTA5.exe+0x110C47C
Found 'SPIDN' GTA5.exe+0x110E7D4
Found 'SVGDN' GTA5.exe+0x1115F08
Found 'GVGAS' GTA5.exe+0x10F0240
Found 'HJR' GTA5.exe+0x1174410
Found 'WJRD' GTA5.exe+0x117507C
Found 'QP' GTA5.exe+0x144539E
Found 'SGS' GTA5.exe+0x1187F80
Found 'APTS' GTA5.exe+0x11E4A14
Found 'SCNM' GTA5.exe+0x11E4DCA
Found 'PMFR' GTA5.exe+0x13FAF8C
Found 'SPDM' GTA5.exe+0x1118348
Found 'SPDM' GTA5.exe+0x1271759
Found 'IMSV' GTA5.exe+0x1152F81
Found 'SND' GTA5.exe+0xF4CCEF
Found 'RR' GTA5.exe+0xC0C74F
Found 'GCP&SRGC' GTA5.exe+0x11E5C1A
Found 'HRGC' GTA5.exe+0x11DEA9E
Found 'BNA' GTA5.exe+0x16ACAB4
Found 'BP' GTA5.exe+0x16ACC9E
Found 'RS' GTA5.exe+0x362C505
Found 'SPDM' GTA5.exe+0x13D807C
Found 'STOPVT' GTA5.exe+0x69A3FC
Found 'CD' GTA5.exe+0x18CB93
Found 'SCI' GTA5.exe+0x13CEA53
Found 'CSH' GTA5.exe+0xA3435C
Found 'CW' GTA5.exe+0x16439F
Found 'WBGH' GTA5.exe+0x1149B70
Found 'RBGH' GTA5.exe+0x1149C60
Found 'CAC' GTA5.exe+0x146F638
Found 'IDC' GTA5.exe+0x6768E8
Found 'ESI' GTA5.exe+0x1407824
Found 'DSI' GTA5.exe+0x13E11E8
Found 'CSSJC' GTA5.exe+0x1154ADA
Found 'CSJJC' GTA5.exe+0x15EA11E
Found 'NTQVMC' GTA5.exe+0x1506179
Found 'MFO' GTA5.exe+0xA6FA4B
Found 'LCF' GTA5.exe+0x5D7240
Found 'SAACF' GTA5.exe+0xA8AC1C
Found 'SJD' GTA5.exe+0xA8A7C0
Found 'NT' GTA5.exe+0xCCBD96
Found 'SNT' GTA5.exe+0x144CE3D
Found 'QD' GTA5.exe+0x12E2A04
Found 'ICF' GTA5.exe+0xA9F9DB
[00:04:05][DEBUG/module.cpp:49]: Waiting for socialclub.dll...
Found 'PD' GTA5.exe+0xC4EF8
[00:04:10][INFO/main.cpp:75]: Pointers initialized.
[00:04:13][INFO/main.cpp:78]: Renderer initialized.
[00:04:13][INFO/main.cpp:82]: Fiber pool initialized.
[00:04:13][INFO/main.cpp:85]: Hooking initialized.
[00:04:13][DEBUG/gta_data_service.cpp:134]: Loading data from cache.
[00:04:13][INFO/gta_data_service.cpp:146]: Loading 336 peds from cache.
[00:04:13][INFO/gta_data_service.cpp:164]: Loading 793 vehicles from cache.
[00:04:13][INFO/gta_data_service.cpp:182]: Loading 295 weapons from cache.
[00:04:13][DEBUG/gta_data_service.cpp:140]: Loaded all data from cache.
[00:04:13][INFO/main.cpp:105]: Registered service instances...
[00:04:13][INFO/main.cpp:122]: Scripts registered.
[00:04:13][INFO/main.cpp:125]: Hooking enabled.
[00:04:13][INFO/main.cpp:128]: Dynamic native hooker initialized.
[00:05:37][INFO/backend.cpp:29]: Starting script: Self
[00:05:37][INFO/backend.cpp:55]: Starting script: Weapons
[00:05:37][INFO/backend.cpp:80]: Starting script: Vehicles
[00:05:37][INFO/backend.cpp:115]: Starting script: Miscellaneous
[00:05:37][INFO/backend.cpp:133]: Starting script: Remote
[00:05:37][INFO/backend.cpp:147]: Starting script: No clip
[00:05:37][INFO/backend.cpp:159]: Starting script: Ls customs
[00:05:37][INFO/backend.cpp:171]: Starting script: Rainbow paint
[00:05:37][INFO/backend.cpp:183]: Starting script: Vehicle fly
[00:05:37][INFO/backend.cpp:103]: Starting script: turnsignal
[00:05:37][INFO/backend.cpp:195]: Starting script: Disable Control Action
[00:10:37][INFO/queue_dependency.cpp:10]: Prevent attempt to queue a report to R*.
[00:12:02][INFO/network_player_mgr.cpp:10]: CNetworkPlayerMgr#init got called, we're probably entering a session.
[00:12:02][INFO/assign_physical_index.cpp:43]: Player joined 'lanch74' allocating slot #0 with Rockstar ID: 124578367
[00:12:04][DEBUG/script_function.cpp:33]: Found pattern SFSA in script freemode
2022/12/21 00:12:15 263574

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 1132

*******	STACKDUMP *******

Loaded Modules:

C:\Program Files (x86)\Steam\gameoverlayrenderer64.dll Base Address: 0x4DFC0000 Size: 0x188000
C:\Program Files (x86)\Steam\steamclient64.dll Base Address: 0x138000000 Size: 0x1581000
C:\Program Files\Rockstar Games\Social Club\chrome_elf.dll Base Address: 0x6A6C0000 Size: 0x101000
C:\Program Files\Rockstar Games\Social Club\libcef.dll Base Address: 0x6F610000 Size: 0x809F000
C:\Program Files\Rockstar Games\Social Club\socialclub.dll Base Address: 0x6C420000 Size: 0xB9B000
C:\windows\system32\COMDLG32.dll Base Address: 0x31F800000 Size: 0xFF000
C:\windows\system32\CRYPT32.dll Base Address: 0x1DD3F0000 Size: 0xCF000
C:\windows\system32\CRYPTUI.dll Base Address: 0x3BB250000 Size: 0x108000
C:\windows\system32\D3D10_1.DLL Base Address: 0x2C77E0000 Size: 0x10000
C:\windows\system32\D3D11.DLL Base Address: 0x359050000 Size: 0x360000
C:\windows\system32\D3DCOMPILER_43.dll Base Address: 0x960000 Size: 0x26F000
C:\windows\system32\D3DCOMPILER_47.dll Base Address: 0x1C8890000 Size: 0x51000
C:\windows\system32\DINPUT8.dll Base Address: 0x308050000 Size: 0x4B000
C:\windows\system32\DSOUND.dll Base Address: 0x236DF0000 Size: 0x5B000
C:\windows\system32\DWrite.dll Base Address: 0x30A950000 Size: 0x72000
C:\windows\system32\ESENT.dll Base Address: 0x2F3920000 Size: 0x10000
C:\windows\system32\IMM32.dll Base Address: 0x3AFD00000 Size: 0x1A000
C:\windows\system32\IPHLPAPI.DLL Base Address: 0x240030000 Size: 0x2D000
C:\windows\system32\Kerberos.dll Base Address: 0x274A50000 Size: 0xD000
C:\windows\system32\ [...]

2022-12-20 19:19 UTC, tupoy-ya commented on src/gta/net_game_event.hpp
> +		char pad_[0x43]; // !FIXME: THIS IS AWFUL BUT I'M TOO STUPID TO FIX IT. tupoy.
This has to be fixed.

2022-12-27 15:42 UTC, maybegreat48 commented on src/gta/net_game_event.hpp
> +		char pad_[0x43]; // !FIXME: THIS IS AWFUL BUT I'M TOO STUPID TO FIX IT. tupoy.
What do you need the padding for?

2022-12-27 15:49 UTC, tupoy-ya commented on src/gta/net_game_event.hpp
> +		char pad_[0x43]; // !FIXME: THIS IS AWFUL BUT I'M TOO STUPID TO FIX IT. tupoy.
`static_assert(sizeof(sEntityDamagedData) == 0x68);` will fail otherwise because size will be 0x25

2022-12-27 16:06 UTC, maybegreat48 commented on src/gta/net_game_event.hpp
> +		char pad_[0x43]; // !FIXME: THIS IS AWFUL BUT I'M TOO STUPID TO FIX IT. tupoy.
Uh oh, padding isn't going to fix the underlying issue which is that `alignas` doesn't seem to work in MinGW. I'm currently making huge global structures that rely on it extensively so the build is going to break if we don't get that fixed

2022-12-27 16:21 UTC, tupoy-ya commented on src/gta/net_game_event.hpp
> +		char pad_[0x43]; // !FIXME: THIS IS AWFUL BUT I'M TOO STUPID TO FIX IT. tupoy.
I know that padding doesn't fix it, i just added padding so it can compile.

2023-06-17 08:52 UTC, tupoy-ya commented
I had to remove signature scanning from `pointers.cpp` because #1227 uses a C++ 20 extension that is not supported by anything except the MSVC compiler. Even Visual Studio doesn't support it.

Is there any other way to implement ptr cache?

2023-06-17 08:57 UTC, xiaoxiao921 commented
Yes.

https://godbolt.org/z/5Kdesxfq3

2023-11-30 13:11 UTC, xiaoxiao921 commented
What's the reason to not use 

msvc-x64-cmake provided by the msvc-wine-git aur package and similar packages? I've had multiple Linux under arch systems and similar successfully compiling

2023-11-30 13:27 UTC, tupoy-ya commented
> What's the reason to not use
> 
> msvc-x64-cmake provided by the msvc-wine-git aur package and similar packages? I've had multiple people with Linux under arch systems and similar successfully compiling

I already use msvc-wine, but i want clangd language server and i don't want to run wine all the time.

Right now I'm using clang with msvc headers to compile YimMenu, and the main problem was `pointers.cpp`.
So I'm just waiting for support from clang, and while i wait i might as well fix everything else, and use the temporary solution of removing the ptr cache.

Ah and also i think cpr did not work with msvc-wine some time ago, but maybe i did something wrong.

2023-11-30 13:53 UTC, xiaoxiao921 commented
I see, you can fix up pointers.cpp by explicitly using a compile time string struct ( there is one in common.hpp) and not using inline struct declaration  inside the template parameters or at least be explicit about the constructor should fix it. For Lua imgui bindings they work under msvc wine, unsure about the other compilers

2024-09-24 21:29 UTC, closed without merging