feat(Fun) #495 #635
YimMenu/YimMenu pull request #649
Opened 2022-11-28 12:52 UTC by Aure7138

feat(self): Fast Respawn
feat(weapon): Rapid Fire (#495)
chore(code clean): util::water (#635)
    deleted util::water and the code in self godmode and vehicle_godmode, which is repeated with proof_water, and it is better to 
    wrap it as a helper function in a class than in a util

2022-11-28 13:21 UTC, Yimura requested changes

2022-11-28 13:21 UTC, Yimura commented on src/backend/looped/self/fast_respawn.cpp
> +        }
Weird indents

2022-11-28 13:21 UTC, Yimura commented on src/backend/looped/weapons/rapid_fire.cpp
> +        }
Weird indents

2022-11-28 13:51 UTC, Aure7138 commented on src/backend/looped/weapons/rapid_fire.cpp
> +        }
fix

2022-11-28 17:20 UTC, Yimura requested changes

2022-11-28 17:20 UTC, Yimura commented on src/backend/looped/self/fast_respawn.cpp
> +	}
Mixed indenting, tabs and soft tabs (spaces)

2022-11-28 17:20 UTC, Yimura commented on src/backend/looped/weapons/rapid_fire.cpp
> +	}
Mixed indenting, tabs and soft tabs (spaces)

2022-11-28 17:47 UTC, TheGreenBandit commented
Why have it if they arent in a vehicle? Why not in a vehicle too?

2022-11-28 18:38 UTC, Aure7138 commented
> Why have it if they arent in a vehicle? Why not in a vehicle too?

Do you mean why add the rapid fire feature because you don't look like you want to have it in or out of the car
But that's your open issue lmao

> Why not in a vehicle too?

Personal preference, I added this function mainly to be able to shoot RPG quickly, and RPG cannot be used in the car, so

2022-11-28 18:38 UTC, Aure7138 commented on src/backend/looped/weapons/rapid_fire.cpp
> +	}
fix

2022-11-28 18:47 UTC, Yimura approved these changes, later dismissed

2022-11-28 22:32 UTC, TheGreenBandit commented
> > Why have it if they arent in a vehicle? Why not in a vehicle too?
> 
> Do you mean why add the rapid fire feature because you don't look like you want to have it in or out of the car But that's your open issue lmao
> 
no i mean the same question i asked after, should've used a comma, grammatical mistake on my end

2022-11-28 22:33 UTC, TheGreenBandit commented
but i would just have it changed so people can use it in a vehicle too because you are forgetting that there aare other weapons to be used in vehicles.

2022-11-29 19:14 UTC, Yimura approved these changes

2022-11-29 19:16 UTC, merged