feat: Some small additions
YimMenu/YimMenu pull request #755
Opened 2022-12-26 15:28 UTC by BugisoftRSG

2022-12-26 17:54 UTC, maybegreat48 commented on src/native_hooks/native_hooks.cpp
> +		add_native_detour(RAGE_JOAAT("fm_lts_creator"), 0x3D3D8B3BE5A83D35, creator::GET_USED_CREATOR_BUDGET);
There is also `fm_survival_creator`. I didn't hook it for the rest of the natives because that creator script cannot be bought online with ease

2022-12-26 17:55 UTC, maybegreat48 commented on src/views/world/view_creator.cpp
> +		ImGui::Checkbox("Infinity Model Memory", &g.ugc.infinity_model_memory);
"Infinite Model Memory" would be better

2022-12-26 17:56 UTC, maybegreat48 commented on src/util/mobile.hpp
> +		inline void request_bin_laden()
I know its funny but I can't easily understand what it does by looking at it

2022-12-26 18:07 UTC, BugisoftRSG commented on src/util/mobile.hpp
> +		inline void request_bin_laden()
:c

2022-12-27 21:15 UTC, Yimura requested changes

2022-12-27 21:15 UTC, Yimura commented on src/views/world/view_creator.cpp
> +			ImGui::SetTooltip("Infinity Model Memory is only useful if dev mode is not activated");
`Infinity` => `Infinite`

2022-12-30 01:09 UTC, Yimura approved these changes

2022-12-30 01:09 UTC, merged