fix issues
YimMenu/YimMenu pull request #869
Opened 2023-01-15 17:45 UTC by TheGreenBandit

completed #868 and fixed error in #862

2023-01-15 20:28 UTC, LiamD-Flop requested changes
Remove the disable control from view_spoofing.cpp
https://github.com/YimMenu/YimMenu/blob/5e3af39854d6799ccb74e1d15b58536f9b7b8bfa/src/views/network/view_spoofing.cpp#L12-L14

2023-01-15 20:28 UTC, LiamD-Flop commented on src/gui/components/input_text.cpp
> +				});
Fix indentation

2023-01-15 22:14 UTC, maybegreat48 commented on src/core/globals.hpp
> -			interloper_reaction breakup_others{ "Breakup Kicks On Other Players", "%s is trying to breakup kick %s!", "%s is trying to breakup kick %s!", true, true }; // blockable only when host but we have
This doesn't fix the issue, I will open a PR that actually fixes it soon

2023-01-16 01:16 UTC, TheGreenBandit commented on src/core/globals.hpp
> -			interloper_reaction breakup_others{ "Breakup Kicks On Other Players", "%s is trying to breakup kick %s!", "%s is trying to breakup kick %s!", true, true }; // blockable only when host but we have
alr ill remove this part then

2023-01-16 20:57 UTC, Yimura approved these changes

2023-01-16 20:58 UTC, merged