added some debug options
YimMenu/YimMenu pull request #883
Opened 2023-01-19 03:51 UTC by TheGreenBandit

Saw the tab empty and thought why not fill it. If anyone has anything to add comment.

2023-01-19 06:18 UTC, Yimura commented
How are these features related to locals? They fit better under the Misc tab.

2023-01-19 10:55 UTC, TheGreenBandit commented
Skip cutscene maybe, i just put in the ones that are clientside

2023-01-19 11:01 UTC, Yimura commented
The locals tab is meant to debug script locals and does to not relate to anything client side in the way you describe it.

2023-01-19 11:27 UTC, TheGreenBandit commented
> The locals tab is meant to debug script locals and does to not relate to anything client side in the way you describe it.

Ah alright, yeah i saw it totally different than it was my bad, ill just move the additions to misc and they can be used there

2023-01-22 21:56 UTC, Yimura approved these changes

2023-01-22 21:59 UTC, Yimura requested changes

2023-01-22 21:59 UTC, Yimura commented on src/views/debug/view_debug_locals.cpp
> +#include "natives.hpp"
Removed unused includes.

2023-01-23 10:43 UTC, Yimura approved these changes

2023-01-23 10:56 UTC, merged