feat(world): nearby options
YimMenu/YimMenu pull request #975
Opened 2023-02-10 21:20 UTC by Seanghost117

Added nearby options to the world section:
[ Peds ]
- Delete nearby peds
- Kill nearby peds
- Kill nearby enemies (most critical important feature: https://www.unknowncheats.me/forum/3675913-post762.html)
- Peds Ignore
- Ped Rain (Just rains the nearby peds until they hit the ground and repeats)
- High Alert (Increase ped perception of nearby peds
- Ped Rush (sets the peds movement so that they move quickly
[ Vehicles ]
- Delete
- Max Upgrade
- Fully Downgrade

[ Blackholes Changes ]
- Added a slider to change the radius of black holes
- Changed the toggles to command toggles

[ Misc ]
- Moved Primexz's get entity function to entities
- Extended buttons so that they can support sizing and color changes (maybe not the best way for colors but it works)

Suggest anything to add, please don't merge this in yet I want to hear some suggestions and fix up how the UI is, I'm going to make use of the sizing hack and make the buttons equal in sizing and spacing. Also mem leak?

2023-02-10 21:33 UTC, Yimura submitted a review, later dismissed
Looks good to me for now.

2023-02-10 22:49 UTC, maybegreat48 commented on src/backend/looped/world/nearby/ignore.cpp
> +		virtual void on_tick() override
Untested, but

on_enable
```
PLAYER::SET_EVERYONE_IGNORE_PLAYER(self::id, true);
PLAYER::SET_POLICE_IGNORE_PLAYER(self::id, true);
```

on_tick
```
EVENT::SUPPRESS_SHOCKING_EVENTS_NEXT_FRAME();
EVENT::SUPPRESS_AGITATION_EVENTS_NEXT_FRAME();
```

on_disable
```
PLAYER::SET_EVERYONE_IGNORE_PLAYER(self::id, false);
PLAYER::SET_POLICE_IGNORE_PLAYER(self::id, false);
```

2023-02-10 22:51 UTC, maybegreat48 commented on src/backend/looped/world/nearby/peds_rain.cpp
> +				if (!ENTITY::IS_ENTITY_IN_AIR(ped)) { // Flag 17 = PED_FLAG_BLOCK_NON_TEMPORARY_EVENTS
`PED_FLAG_BLOCK_NON_TEMPORARY_EVENTS` what?

2023-02-10 22:53 UTC, Seanghost117 commented on src/backend/looped/world/nearby/peds_rain.cpp
> +				if (!ENTITY::IS_ENTITY_IN_AIR(ped)) { // Flag 17 = PED_FLAG_BLOCK_NON_TEMPORARY_EVENTS
accidental comment I left, was in ignore.cpp

2023-02-10 22:54 UTC, maybegreat48 commented on src/util/vehicle.hpp
> +		VEHICLE::REMOVE_VEHICLE_MOD(vehicle, 18); //Remove turbo on vehicle
Doesn't the above loop remove 18 and 22?

2023-02-10 23:20 UTC, maybegreat48 commented on src/backend/looped/world/nearby/ignore.cpp
> +		virtual void on_tick() override
Can you test the `on_tick` part? Getting all peds for an ignore player feature seems too performance intensive IMO

2023-02-10 23:21 UTC, maybegreat48 commented on src/backend/looped/world/nearby/high_alert.cpp
> +			{
Reset on `on_disable`. Same for the speed thing

2023-02-10 23:22 UTC, Seanghost117 commented on src/backend/looped/world/nearby/high_alert.cpp
> +			{
right, thanks

2023-02-11 00:06 UTC, Seanghost117 commented
![image](https://user-images.githubusercontent.com/36561158/218224500-94cfc9c1-4eca-4206-9e4a-a947866fb8b1.png)
Tried to match the colors to the vibe

2023-02-13 07:17 UTC, Seanghost117 commented
**Update**
I changed the PR title as I've expanded this PR to more than just nearby options, I've added the following

[ Weapons ]
- Added aimbot
- Added fov, smoothing, and smoothing speed to aimbot options

[ GUI ]
- Added templating to components::button, seemed kind of weird to just throw it all in at the end, let me know if this is a problem @Yimura and I'll fix it

This should handle #965 , takes over part of #889 by @TheGreenBandit 
To Do:

- [ ] Added ped relation check (for enemies, cops, etc)
- [ ] Add Ped Bone selector for aimbot
- [ ] Update triggerbot to tap peds in vehicles as well
- [ ] Include players
- [ ] Distance check on the aimbot (and maybe triggerbot), limited by max range anyways

@maybegreat48 let me know if you have any suggestions or if I missed something in this commit

2023-02-13 10:48 UTC, maybegreat48 commented on src/backend/looped/weapons/triggerbot.cpp
> +				if (entity::raycast(&crosshair_catch))
Does `GET_ENTITY_PLAYER_IS_FREE_AIMING_AT` work? That native is no longer detected after the anticheat changes

2023-02-13 11:27 UTC, Seanghost117 commented on src/backend/looped/weapons/triggerbot.cpp
> +				if (entity::raycast(&crosshair_catch))
It actually did work, that’s what I had it set to before but opted for raycast for uniformity

2023-02-17 15:57 UTC, TheGreenBandit commented
For the distance check just compare self::pos to the bone position using SYSTEM::VDIST

2023-02-17 15:59 UTC, Seanghost117 commented
> For the distance check just compare self::pos to the bone position using SYSTEM::VDIST

Distance and entities checks should be done, haven’t staged the commit yet, got to work on players later today if I have free time thought.

2023-02-18 16:52 UTC, Seanghost117 commented
Done with the aimbot, if there are any suggestions you can leave them but they will be done at a later time with the prediction, I'm going to add and edit some nearby features and switch it to review before I sit on it for too long

2023-02-18 16:57 UTC, BeztNA commented
> Done with the aimbot, if there are any suggestions you can leave them but they will be done at a later time with the prediction, I'm going to add and edit some nearby features and switch it to review before I sit on it for too long
can u add heist editor sir ?

2023-02-18 16:59 UTC, Seanghost117 commented
> Done with the aimbot, if there are any suggestions you can leave them but they will be done at a later time with the prediction, I'm going to add and edit some nearby features and switch it to review before I sit on it for too long

Will probably just add options for editing the color of nearby vehicles, fucking with them, and whatever else. Delete vehicles is buggy so will remove it for now. Also, it seems ped ignore can be a good alternative for evading the law without actually editing your wanted level

> > Done with the aimbot, if there are any suggestions you can leave them but they will be done at a later time with the prediction, I'm going to add and edit some nearby features and switch it to review before I sit on it for too long

> > can u add heist editor sir ?
No, this will not be added, especially since it falls too close to recovery.

2023-02-18 17:03 UTC, BeztNA commented
> > Done with the aimbot, if there are any suggestions you can leave them but they will be done at a later time with the prediction, I'm going to add and edit some nearby features and switch it to review before I sit on it for too long
> 
> Will probably just add options for editing the color of nearby vehicles, fucking with them, and whatever else. Delete vehicles is buggy so will remove it for now. Also, it seems ped ignore can be a good alternative for evading the law without actually editing your wanted level
> 
> > can u add heist editor sir ?
> 
> No, this will not be added, especially since it falls too close to recovery.

thanks for answer, but when do this pr release ?

2023-02-18 17:05 UTC, Seanghost117 commented
I will try to get this pushed within a few hours tops. I'm just going to step out to eat first

2023-02-18 17:06 UTC, BeztNA commented
> I will try to get this pushed within a few hours tops. I'm just going to step out to eat first

tks u

2023-02-20 13:48 UTC, PrimeMK105 commented
> Done with the aimbot, if there are any suggestions you can leave them but they will be done at a later time with the prediction, I'm going to add and edit some nearby features and switch it to review before I sit on it for too long

Option to not shoot at friends/people who in your organization/motoclub?

2023-02-21 13:08 UTC, Yimura requested changes
I messed up merging the code and broke the build, I'll fix that when I get home.

2023-02-21 13:08 UTC, Yimura commented on src/backend/looped/weapons/aimbot.cpp
> +					else if (g.weapons.aimbot.on_npc && !PED::IS_PED_A_PLAYER(ped))
Could you redo this code without using `goto` and adding some curly brackets after the if statements.

2023-02-21 13:08 UTC, Yimura commented on src/backend/looped/world/nearby/vehicles_rain.cpp
> +
Random newline.

2023-02-21 13:08 UTC, Yimura commented on src/backend/looped/world/nearby/vehicles_rain.cpp
> +		}
Mixed curly brace placement, preferably have the opening curly bracket start on a newline.

2023-02-21 13:08 UTC, Yimura commented on src/core/globals.hpp
> +			} aimbot{};
newline after struct definition

2023-02-21 13:08 UTC, Yimura commented on src/gui/components/components.hpp
> +				status = false;
```cpp
status = ImGui::Button(text.data(), size);
```

2023-02-21 13:08 UTC, Yimura commented on src/gui/components/components.hpp
> +		}
Newline below function

2023-02-21 13:08 UTC, Yimura commented on src/views/self/view_weapons.cpp
> +		if (g.weapons.aimbot.enable) {
curly bracket on newline

2023-02-21 13:08 UTC, Yimura commented on src/views/world/view_nearby.cpp
> +				}
Wrap if between curly brackets and also opening curly bracket on newline

2023-02-21 13:08 UTC, Yimura commented on src/views/world/view_nearby.cpp
> +			});
Not very readable though I'm open for suggestions.

```cpp
components::button<ImVec2(110, 0)> ("Delete", []
{ 
	for (auto peds : entity::get_entities(false, true))
		entity::delete_entity(peds); 
}); ImGui::SameLine();
components::button<ImVec2(110, 0), ImVec4(0.70196f, 0.3333f, 0.00392f, 1.f)>("Kill", []
{ 
	for (auto peds : entity::get_entities(false, true))
		ped::kill_ped(peds); 
}); ImGui::SameLine();
components::button<ImVec2(110, 0), ImVec4(0.76078f, 0.f, 0.03529f, 1.f)>("Kill Enemies", []
{ 
	for (auto peds : entity::get_entities(false, true))
		ped::kill_ped_by_relation(peds, 4 || 5); 
});
```

Same for "Max Upgrade" & "Downgrade" options below

2023-02-21 15:00 UTC, Seanghost117 commented on src/backend/looped/world/nearby/vehicles_rain.cpp
> +
fixed

2023-02-21 19:16 UTC, Yimura commented on src/backend/looped/weapons/aimbot.cpp
> +					else if (g.weapons.aimbot.on_npc && !PED::IS_PED_A_PLAYER(ped))
I'm fine with just adding curly braces if the goto's make the code flow easier.

2023-02-22 13:08 UTC, BeztNA commented
when do this pr release sir ?

2023-02-22 13:41 UTC, TheGreenBandit commented
> when do this pr release sir ?

When it is considered polished and ready by sean

2023-02-25 20:23 UTC, Yimura approved these changes
Thanks a lot for adding so many new features, waiting for CI to finish and then I'll merge it.

2023-02-25 20:33 UTC, merged